<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ActorRoleTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('actor_role')->insertOrIgnore([

            [
                'code' => 'ADV',
                'name' => json_encode(['en' => 'Adversary', 'fr' => 'Adversaire', 'de' => 'Gegenpartei']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 1,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'AGT',
                'name' => json_encode(['en' => 'Primary Agent', 'fr' => 'Agent principal', 'de' => 'Hauptvertreter']),
                'display_order' => 20,
                'shareable' => 0,
                'show_ref' => 1,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'AGT2',
                'name' => json_encode(['en' => 'Secondary Agent', 'fr' => 'Agent secondaire', 'de' => 'Zweitvertreter']),
                'display_order' => 22,
                'shareable' => 0,
                'show_ref' => 1,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => 'Usually the primary agent\'s agent',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'ANN',
                'name' => json_encode(['en' => 'Annuity Agent', 'fr' => 'Agent annuités', 'de' => 'Jahresgebührenvertreter']),
                'display_order' => 21,
                'shareable' => 0,
                'show_ref' => 1,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'APP',
                'name' => json_encode(['en' => 'Applicant', 'fr' => 'Déposant', 'de' => 'Anmelder']),
                'display_order' => 10,
                'shareable' => 1,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'CLI',
                'name' => json_encode(['en' => 'Client', 'fr' => 'Client', 'de' => 'Mandant']),
                'display_order' => 5,
                'shareable' => 1,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 1,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'CNT',
                'name' => json_encode(['en' => 'Contact', 'fr' => 'Contact', 'de' => 'Kontakt']),
                'display_order' => 30,
                'shareable' => 1,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'DBA',
                'name' => json_encode(['en' => 'DB Administrator', 'fr' => 'BDD Admin.', 'de' => 'DB-Administrator']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'DBRO',
                'name' => json_encode(['en' => 'DB Read-Only', 'fr' => 'BDD Lecture seule', 'de' => 'DB Nur-Lesezugriff']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'DBRW',
                'name' => json_encode(['en' => 'DB Read/Write', 'fr' => 'BDD Lecture/écriture', 'de' => 'DB Lese-/Schreibzugriff']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'DEL',
                'name' => json_encode(['en' => 'Delegate', 'fr' => 'Délégataire', 'de' => 'Bevollmächtigter']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'FAGT',
                'name' => json_encode(['en' => 'Former Agent', 'fr' => 'Ancien agent', 'de' => 'Ehemaliger Vertreter']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 1,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'FOWN',
                'name' => json_encode(['en' => 'Former Owner', 'fr' => 'Ancien titulairte', 'de' => 'Ehemaliger Inhaber']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'INV',
                'name' => json_encode(['en' => 'Inventor', 'fr' => 'Inventeur', 'de' => 'Erfinder']),
                'display_order' => 15,
                'shareable' => 1,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'LCN',
                'name' => json_encode(['en' => 'Licensee', 'fr' => 'Licencié', 'de' => 'Lizenznehmer']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'OFF',
                'name' => json_encode(['en' => 'Patent Office', 'fr' => 'Office des brevets', 'de' => 'Patentamt']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'OPP',
                'name' => json_encode(['en' => 'Opponent', 'fr' => 'Opposant', 'de' => 'Einsprechender']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'OWN',
                'name' => json_encode(['en' => 'Owner', 'fr' => 'Titulaire', 'de' => 'Inhaber']),
                'display_order' => 8,
                'shareable' => 1,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PAY',
                'name' => json_encode(['en' => 'Payor', 'fr' => 'Payeur', 'de' => 'Zahler']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PTNR',
                'name' => json_encode(['en' => 'Partner', 'fr' => 'Partenaire', 'de' => 'Partner']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 0,
                'show_date' => 1,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'TRA',
                'name' => json_encode(['en' => 'Translator', 'fr' => 'Traducteur', 'de' => 'Übersetzer']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 1,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'WRI',
                'name' => json_encode(['en' => 'Writer', 'fr' => 'Rédacteur', 'de' => 'Verfasser']),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 1,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}