<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ActorRoleTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('actor_role')->insertOrIgnore(array(

            array(
                'code' => 'AGT',
                'name' => 'Primary Agent',
                'display_order' => 20,
                'shareable' => 0,
                'show_ref' => 1,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'code' => 'AGT2',
                'name' => 'Secondary Agent',
                'display_order' => 22,
                'shareable' => 0,
                'show_ref' => 1,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => 'Usually the primary agent\'s agent',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'code' => 'ANN',
                'name' => 'Annuity Agent',
                'display_order' => 21,
                'shareable' => 0,
                'show_ref' => 1,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => 'Agent in charge of renewals. -Client handled- is a special agent who, when added, will delete any renewals in the matter',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'code' => 'APP',
                'name' => 'Applicant',
                'display_order' => 3,
                'shareable' => 1,
                'show_ref' => 1,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => 'Assignee in the US, i.e. the owner upon filing',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'code' => 'CLI',
                'name' => 'Client',
                'display_order' => 1,
                'shareable' => 1,
                'show_ref' => 1,
                'show_company' => 0,
                'show_rate' => 1,
                'show_date' => 0,
                'notes' => 'The client we take instructions from and who we invoice. DO NOT CHANGE OR DELETE: this is also a database user role',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'code' => 'CNT',
                'name' => 'Contact',
                'display_order' => 30,
                'shareable' => 1,
                'show_ref' => 1,
                'show_company' => 1,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => 'Client\'s contact person',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'code' => 'DBA',
                'name' => 'DB Administrator',
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'code' => 'DBRO',
                'name' => 'DB Read-Only',
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'code' => 'DBRW',
                'name' => 'DB Read/Write',
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'code' => 'DEL',
                'name' => 'Delegate',
                'display_order' => 31,
                'shareable' => 1,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => 'Another user allowed to manage the case',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'code' => 'FAGT',
                'name' => 'Former Agent',
                'display_order' => 23,
                'shareable' => 0,
                'show_ref' => 1,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'code' => 'FOWN',
                'name' => 'Former Owner',
                'display_order' => 5,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 1,
                'notes' => 'To keep track of ownership history',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'code' => 'INV',
                'name' => 'Inventor',
                'display_order' => 10,
                'shareable' => 1,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'code' => 'LCN',
                'name' => 'Licensee',
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'code' => 'OFF',
                'name' => 'Patent Office',
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'code' => 'OPP',
                'name' => 'Opposing Party',
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'code' => 'OWN',
                'name' => 'Owner',
                'display_order' => 4,
                'shareable' => 0,
                'show_ref' => 1,
                'show_company' => 0,
                'show_rate' => 1,
                'show_date' => 1,
                'notes' => 'Use if different than applicant',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'code' => 'PAY',
                'name' => 'Payor',
                'display_order' => 2,
                'shareable' => 1,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 1,
                'show_date' => 0,
                'notes' => 'The actor who pays',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'code' => 'PTNR',
                'name' => 'Partner',
                'display_order' => 127,
                'shareable' => 1,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'code' => 'TRA',
                'name' => 'Translator',
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 1,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ),

            array(
                'code' => 'WRI',
                'name' => 'Writer',
                'display_order' => 127,
                'shareable' => 1,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => 'Person who follows the case',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ),
        ));
    }
}
