<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ActorRoleTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('actor_role')->insertOrIgnore([

            [
                'code' => 'AGT',
                'name' => json_encode('{"name_en": "Primary Agent"}'),
                'display_order' => 20,
                'shareable' => 0,
                'show_ref' => 1,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'AGT2',
                'name' => json_encode('{"name_en": "Secondary Agent"}'),
                'display_order' => 22,
                'shareable' => 0,
                'show_ref' => 1,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => 'Usually the primary agent\'s agent',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'ANN',
                'name' => json_encode('{"name_en": "Annuity Agent"}'),
                'display_order' => 21,
                'shareable' => 0,
                'show_ref' => 1,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => 'Agent in charge of renewals. -Client handled- is a special agent who, when added, will delete any renewals in the matter',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'APP',
                'name' => json_encode('{"name_en": "Applicant"}'),
                'display_order' => 3,
                'shareable' => 1,
                'show_ref' => 1,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => 'Assignee in the US, i.e. the owner upon filing',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'CLI',
                'name' => json_encode('{"name_en": "Client"}'),
                'display_order' => 1,
                'shareable' => 1,
                'show_ref' => 1,
                'show_company' => 0,
                'show_rate' => 1,
                'show_date' => 0,
                'notes' => 'The client we take instructions from and who we invoice. DO NOT CHANGE OR DELETE: this is also a database user role',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'CNT',
                'name' => json_encode('{"name_en": "Contact"}'),
                'display_order' => 30,
                'shareable' => 1,
                'show_ref' => 1,
                'show_company' => 1,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => 'Client\'s contact person',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'DBA',
                'name' => json_encode('{"name_en": "DB Administrator"}'),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'DBRO',
                'name' => json_encode('{"name_en": "DB Read-Only"}'),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'DBRW',
                'name' => json_encode('{"name_en": "DB Read/Write"}'),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'DEL',
                'name' => json_encode('{"name_en": "Delegate"}'),
                'display_order' => 31,
                'shareable' => 1,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => 'Another user allowed to manage the case',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'FAGT',
                'name' => json_encode('{"name_en": "Former Agent"}'),
                'display_order' => 23,
                'shareable' => 0,
                'show_ref' => 1,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'FOWN',
                'name' => json_encode('{"name_en": "Former Owner"}'),
                'display_order' => 5,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 1,
                'notes' => 'To keep track of ownership history',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'INV',
                'name' => json_encode('{"name_en": "Inventor"}'),
                'display_order' => 10,
                'shareable' => 1,
                'show_ref' => 0,
                'show_company' => 1,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'LCN',
                'name' => json_encode('{"name_en": "Licensee"}'),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'OFF',
                'name' => json_encode('{"name_en": "Patent Office"}'),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'OPP',
                'name' => json_encode('{"name_en": "Opposing Party"}'),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'OWN',
                'name' => json_encode('{"name_en": "Owner"}'),
                'display_order' => 4,
                'shareable' => 0,
                'show_ref' => 1,
                'show_company' => 0,
                'show_rate' => 1,
                'show_date' => 1,
                'notes' => 'Use if different than applicant',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PAY',
                'name' => json_encode('{"name_en": "Payor"}'),
                'display_order' => 2,
                'shareable' => 1,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 1,
                'show_date' => 0,
                'notes' => 'The actor who pays',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PTNR',
                'name' => json_encode('{"name_en": "Partner"}'),
                'display_order' => 127,
                'shareable' => 1,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'TRA',
                'name' => json_encode('{"name_en": "Translator"}'),
                'display_order' => 127,
                'shareable' => 0,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 1,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'WRI',
                'name' => json_encode('{"name_en": "Writer"}'),
                'display_order' => 127,
                'shareable' => 1,
                'show_ref' => 0,
                'show_company' => 0,
                'show_rate' => 0,
                'show_date' => 0,
                'notes' => 'Person who follows the case',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
