<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClassifierTypeTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('classifier_type')->insertOrIgnore([

            [
                'code' => 'ABS',
                'type' => json_encode('{"type_en": "Abstract"}'),
                'main_display' => 0,
                'for_category' => null,
                'display_order' => 127,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'AGR',
                'type' => json_encode('{"type_en": "Agreement"}'),
                'main_display' => 0,
                'for_category' => null,
                'display_order' => 127,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'BU',
                'type' => json_encode('{"type_en": "Business Unit"}'),
                'main_display' => 0,
                'for_category' => null,
                'display_order' => 127,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'DESC',
                'type' => json_encode('{"type_en": "Description"}'),
                'main_display' => 1,
                'for_category' => null,
                'display_order' => 1,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'EVAL',
                'type' => json_encode('{"type_en": "Evaluation"}'),
                'main_display' => 0,
                'for_category' => null,
                'display_order' => 127,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'IMG',
                'type' => json_encode('{"type_en": "Image"}'),
                'main_display' => 0,
                'for_category' => null,
                'display_order' => 127,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'IPC',
                'type' => json_encode('{"type_en": "IPC"}'),
                'main_display' => 0,
                'for_category' => null,
                'display_order' => 127,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'KW',
                'type' => json_encode('{"type_en": "Keyword"}'),
                'main_display' => 0,
                'for_category' => null,
                'display_order' => 127,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'LNK',
                'type' => json_encode('{"type_en": "Link"}'),
                'main_display' => 0,
                'for_category' => null,
                'display_order' => 1,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'LOC',
                'type' => json_encode('{"type_en": "Location"}'),
                'main_display' => 0,
                'for_category' => null,
                'display_order' => 127,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'ORG',
                'type' => json_encode('{"type_en": "Organization"}'),
                'main_display' => 0,
                'for_category' => null,
                'display_order' => 127,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PA',
                'type' => json_encode('{"type_en": "Prior Art"}'),
                'main_display' => 0,
                'for_category' => null,
                'display_order' => 127,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PROD',
                'type' => json_encode('{"type_en": "Product"}'),
                'main_display' => 0,
                'for_category' => null,
                'display_order' => 127,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PROJ',
                'type' => json_encode('{"type_en": "Project"}'),
                'main_display' => 0,
                'for_category' => null,
                'display_order' => 127,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'TECH',
                'type' => json_encode('{"type_en": "Technology"}'),
                'main_display' => 0,
                'for_category' => null,
                'display_order' => 127,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'TIT',
                'type' => json_encode('{"type_en": "Title"}'),
                'main_display' => 1,
                'for_category' => null,
                'display_order' => 1,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'TITAL',
                'type' => json_encode('{"type_en": "Alt. Title"}'),
                'main_display' => 1,
                'for_category' => 'PAT',
                'display_order' => 4,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'TITEN',
                'type' => json_encode('{"type_en": "English Title"}'),
                'main_display' => 1,
                'for_category' => 'PAT',
                'display_order' => 3,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'TITOF',
                'type' => json_encode('{"type_en": "Official Title"}'),
                'main_display' => 1,
                'for_category' => 'PAT',
                'display_order' => 2,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'TM',
                'type' => json_encode('{"type_en": "Trademark"}'),
                'main_display' => 1,
                'for_category' => 'TM',
                'display_order' => 1,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'TMCL',
                'type' => json_encode('{"type_en": "Class (TM)"}'),
                'main_display' => 0,
                'for_category' => 'TM',
                'display_order' => 2,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'TMTYP',
                'type' => json_encode('{"type_en": "Type (TM)"}'),
                'main_display' => 0,
                'for_category' => 'TM',
                'display_order' => 3,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
