<?php
$classifier_type = [
  ['code' => 'ABS', 'type' => 'Abstract', 'main_display' => 0, 'for_category' => NULL, 'display_order' => 127],
  ['code' => 'AGR', 'type' => 'Agreement', 'main_display' => 0, 'for_category' => NULL, 'display_order' => 127],
  ['code' => 'BU', 'type' => 'Business Unit', 'main_display' => 0, 'for_category' => NULL, 'display_order' => 127],
  ['code' => 'DESC', 'type' => 'Description', 'main_display' => 1, 'for_category' => NULL, 'display_order' => 1],
  ['code' => 'EVAL', 'type' => 'Evaluation', 'main_display' => 0, 'for_category' => NULL, 'display_order' => 127],
  ['code' => 'IMG', 'type' => 'Image', 'main_display' => 0, 'for_category' => NULL, 'display_order' => 127],
  ['code' => 'IPC', 'type' => 'IPC', 'main_display' => 0, 'for_category' => NULL, 'display_order' => 127],
  ['code' => 'KW', 'type' => 'Keyword', 'main_display' => 0, 'for_category' => NULL, 'display_order' => 127],
  ['code' => 'LNK', 'type' => 'Link', 'main_display' => 0, 'for_category' => NULL, 'display_order' => 1],
  ['code' => 'LOC', 'type' => 'Location', 'main_display' => 0, 'for_category' => NULL, 'display_order' => 127],
  ['code' => 'ORG', 'type' => 'Organization', 'main_display' => 0, 'for_category' => NULL,'display_order' => 127],
  ['code' => 'PA', 'type' => 'Prior Art', 'main_display' => 0, 'for_category' => NULL, 'display_order' => 127],
  ['code' => 'PROD', 'type' => 'Product', 'main_display' => 0, 'for_category' => NULL ,'display_order' => 127],
  ['code' => 'PROJ', 'type' => 'Project', 'main_display' => 0, 'for_category' => NULL, 'display_order' => 127],
  ['code' => 'TECH', 'type' => 'Technology', 'main_display' => 0, 'for_category' => NULL, 'display_order' => 127],
  ['code' => 'TIT', 'type' => 'Title', 'main_display' => 1, 'for_category' => NULL, 'display_order' => 1],
  ['code' => 'TITAL', 'type' => 'Alt. Title', 'main_display' => 1, 'for_category' => 'PAT', 'display_order' => 4],
  ['code' => 'TITEN', 'type' => 'English Title', 'main_display' => 1, 'for_category' => 'PAT', 'display_order' => 3],
  ['code' => 'TITOF', 'type' => 'Official Title', 'main_display' => 1, 'for_category' => 'PAT', 'display_order' => 2],
  ['code' => 'TM', 'type' => 'Trademark', 'main_display' => 1, 'for_category' => 'TM', 'display_order' => 1],
  ['code' => 'TMCL', 'type' => 'Class (TM)', 'main_display' => 0, 'for_category' => 'TM', 'display_order' => 2],
  ['code' => 'TMTYP', 'type' => 'Type (TM)', 'main_display' => 0, 'for_category' => 'TM', 'display_order' => 3]
];
