<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EventNameTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('event_name')->insertOrIgnore([

            [
                'code' => 'ABA',
                'name' => json_encode('{"name_en": "Abandoned"}'),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 1,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'ABO',
                'name' => json_encode('{"name_en": "Abandon Original"}'),
                'category' => 'PAT',
                'country' => 'EP',
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => 'Abandon the originating patent that was re-designated in EP',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'ADV',
                'name' => json_encode('{"name_en": "Advisory Action"}'),
                'category' => 'PAT',
                'country' => 'US',
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'ALL',
                'name' => json_encode('{"name_en": "Allowance"}'),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Use also for R71.3 in EP',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'APL',
                'name' => json_encode('{"name_en": "Appeal"}'),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 1,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Appeal or other remedy filed',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'CAN',
                'name' => json_encode('{"name_en": "Cancelled"}'),
                'category' => 'TM',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 1,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'CLO',
                'name' => json_encode('{"name_en": "Closed"}'),
                'category' => 'LTG',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 1,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'COM',
                'name' => json_encode('{"name_en": "Communication"}'),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Communication regarding administrative or formal matters (missing parts, irregularities...)',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'CRE',
                'name' => json_encode('{"name_en": "Created"}'),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => 'Creation date of matter - for attaching tasks necessary before anything else',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'DAPL',
                'name' => json_encode('{"name_en": "Decision on Appeal"}'),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'State outcome in detail field',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'DBY',
                'name' => json_encode('{"name_en": "Draft By"}'),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 1,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'DEX',
                'name' => json_encode('{"name_en": "Deadline Extended"}'),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Deadline extension requested',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'DPAPL',
                'name' => json_encode('{"name_en": "Decision on Pre-Appeal"}'),
                'category' => 'PAT',
                'country' => 'US',
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'DRA',
                'name' => json_encode('{"name_en": "Drafted"}'),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'DW',
                'name' => json_encode('{"name_en": "Deemed withrawn"}'),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Decision needing a reply, such as further processing',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'EHK',
                'name' => json_encode('{"name_en": "Extend to Hong Kong"}'),
                'category' => 'PAT',
                'country' => 'CN',
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'ENT',
                'name' => json_encode('{"name_en": "Entered"}'),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => 'National entry date from PCT phase',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'EOP',
                'name' => json_encode('{"name_en": "End of Procedure"}'),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 1,
                'notes' => 'Indicates the end of a regional procedure, such as when the EP patent is granted',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'EXA',
                'name' => json_encode('{"name_en": "Examiner Action"}'),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'AKA Office Action, i.e. anything related to substantive examination',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'EXAF',
                'name' => json_encode('{"name_en": "Examiner Action (Final)"}'),
                'category' => 'PAT',
                'country' => 'US',
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'EXP',
                'name' => json_encode('{"name_en": "Expiry"}'),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 1,
                'notes' => 'Do not use nor change - present for internal functionality',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'FAP',
                'name' => json_encode('{"name_en": "File Notice of Appeal"}'),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 1,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'FBY',
                'name' => json_encode('{"name_en": "File by"}'),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'FDIV',
                'name' => json_encode('{"name_en": "File Divisional"}'),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'FIL',
                'name' => json_encode('{"name_en": "Filed"}'),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'FOP',
                'name' => json_encode('{"name_en": "File Opposition"}'),
                'category' => 'OP',
                'country' => 'EP',
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 1,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'FPR',
                'name' => json_encode('{"name_en": "Further Processing"}'),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 1,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'FRCE',
                'name' => json_encode('{"name_en": "File RCE"}'),
                'category' => 'PAT',
                'country' => 'US',
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'GRT',
                'name' => json_encode('{"name_en": "Granted"}'),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'INV',
                'name' => json_encode('{"name_en": "Invalidated"}'),
                'category' => 'TM',
                'country' => 'US',
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 1,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'LAP',
                'name' => json_encode('{"name_en": "Lapsed"}'),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 1,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'NPH',
                'name' => json_encode('{"name_en": "National Phase"}'),
                'category' => 'PAT',
                'country' => 'WO',
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'OPP',
                'name' => json_encode('{"name_en": "Opposition"}'),
                'category' => null,
                'country' => 'EP',
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'OPR',
                'name' => json_encode('{"name_en": "Oral Proceedings"}'),
                'category' => 'PAT',
                'country' => 'EP',
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 1,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'ORE',
                'name' => json_encode('{"name_en": "Opposition rejected"}'),
                'category' => 'PAT',
                'country' => 'EP',
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PAY',
                'name' => json_encode('{"name_en": "Pay"}'),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Use for any fees to be paid',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PDES',
                'name' => json_encode('{"name_en": "Post designation"}'),
                'category' => 'TM',
                'country' => 'WO',
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PFIL',
                'name' => json_encode('{"name_en": "Parent Filed"}'),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => 'Filing date of the parent (use only when the matter type is defined). Use as link to the parent matter.',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PR',
                'name' => json_encode('{"name_en": "Publication of Reg."}'),
                'category' => 'TM',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PREP',
                'name' => json_encode('{"name_en": "Prepare"}'),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 1,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Any further action to be done by the responsible (comments, pre-handling, ...)',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PRI',
                'name' => json_encode('{"name_en": "Priority Claim"}'),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Use as link to the priority matter',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PRID',
                'name' => json_encode('{"name_en": "Priority Deadline"}'),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PROD',
                'name' => json_encode('{"name_en": "Produce"}'),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Any further documents to be filed (inventor designation, priority document, missing parts...)',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PSR',
                'name' => json_encode('{"name_en": "Publication of SR"}'),
                'category' => 'PAT',
                'country' => 'EP',
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => 'A3 publication',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'PUB',
                'name' => json_encode('{"name_en": "Published"}'),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'For EP, this means publication WITH the search report (A1 publ.)',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'RCE',
                'name' => json_encode('{"name_en": "Request Continued Examination"}'),
                'category' => 'PAT',
                'country' => 'US',
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'REC',
                'name' => json_encode('{"name_en": "Received"}'),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => 'Date the case was received from the client',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'REF',
                'name' => json_encode('{"name_en": "Refused"}'),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'This is the final decision, that can only be appealed - do not mistake with an exam report',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'REG',
                'name' => json_encode('{"name_en": "Registration"}'),
                'category' => 'TM',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'REM',
                'name' => json_encode('{"name_en": "Reminder"}'),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'REN',
                'name' => json_encode('{"name_en": "Renewal"}'),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'AKA Annuity',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'REP',
                'name' => json_encode('{"name_en": "Respond"}'),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 1,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Use for any response',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'REQ',
                'name' => json_encode('{"name_en": "Request"}'),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => 'Use for any request',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'RSTR',
                'name' => json_encode('{"name_en": "Restriction Req."}'),
                'category' => 'PAT',
                'country' => 'US',
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'SOL',
                'name' => json_encode('{"name_en": "Sold"}'),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 1,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'SOP',
                'name' => json_encode('{"name_en": "Summons to Oral Proc."}'),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'SR',
                'name' => json_encode('{"name_en": "Search Report"}'),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'SUS',
                'name' => json_encode('{"name_en": "Suspended"}'),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'TRF',
                'name' => json_encode('{"name_en": "Transferred"}'),
                'category' => null,
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 1,
                'notes' => 'Case no longer followed',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'VAL',
                'name' => json_encode('{"name_en": "Validate"}'),
                'category' => 'PAT',
                'country' => 'EP',
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 1,
                'killer' => 0,
                'notes' => 'Validate granted EP in designated countries',
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'WAT',
                'name' => json_encode('{"name_en": "Watch"}'),
                'category' => null,
                'country' => null,
                'is_task' => 1,
                'status_event' => 0,
                'default_responsible' => null,
                'use_matter_resp' => 1,
                'unique' => 0,
                'killer' => 0,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => 'WIT',
                'name' => json_encode('{"name_en": "Withdrawal"}'),
                'category' => 'PAT',
                'country' => null,
                'is_task' => 0,
                'status_event' => 1,
                'default_responsible' => null,
                'use_matter_resp' => 0,
                'unique' => 0,
                'killer' => 1,
                'notes' => null,
                'creator' => 'system',
                'updater' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

    }
}
