<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 4.6.6deb5
 */

/**
 * Database `phpipv2`
 */

/* `phpipv2`.`actor` */
$actor = array(
  array('id' => '124','name' => 'Tesla Motors Inc.','first_name' => NULL,'display_name' => 'Tesla','login' => 'Tesla','password' => '$2y$10$jcKMOnHVpl0cciOTfmCAouIrZ/gQCHxu31oSuThcM/k4YXW/0HruC','password_salt' => NULL,'last_login' => NULL,'default_role' => 'CLI','function' => NULL,'parent_id' => NULL,'company_id' => NULL,'site_id' => NULL,'phy_person' => '0','nationality' => NULL,'small_entity' => '0','address' => '','country' => NULL,'address_mailing' => '','country_mailing' => NULL,'address_billing' => '','country_billing' => NULL,'email' => NULL,'phone' => NULL,'legal_form' => NULL,'registration_no' => NULL,'warn' => '0','notes' => 'TEST DATA','VAT_number' => NULL,'creator' => 'phpipuser','updated' => '2019-02-09 12:17:34','updater' => 'root','remember_token' => 'uuss4o9FKG1BdFExHH4YhCj6VnyliPB5lpnL3KnTfYJNJ2Wh49VaQrY6eaXZ'),
  array('id' => '125','name' => 'BAGLINO Andrew D.','first_name' => NULL,'display_name' => NULL,'login' => NULL,'password' => NULL,'password_salt' => NULL,'last_login' => NULL,'default_role' => 'INV','function' => NULL,'parent_id' => NULL,'company_id' => '124','site_id' => '130','phy_person' => '1','nationality' => 'FR','small_entity' => '0','address' => '','country' => 'US','address_mailing' => '','country_mailing' => NULL,'address_billing' => '','country_billing' => NULL,'email' => NULL,'phone' => NULL,'legal_form' => NULL,'registration_no' => NULL,'warn' => '0','notes' => 'TEST DATA','VAT_number' => NULL,'creator' => 'phpipuser','updated' => '2018-05-24 14:36:08','updater' => 'root','remember_token' => NULL),
  array('id' => '126','name' => 'HAYER','first_name' => 'Thorsten','display_name' => 'HAYER Thorsten','login' => NULL,'password' => NULL,'password_salt' => NULL,'last_login' => NULL,'default_role' => 'INV','function' => NULL,'parent_id' => NULL,'company_id' => '124','site_id' => NULL,'phy_person' => '1','nationality' => NULL,'small_entity' => '0','address' => '','country' => NULL,'address_mailing' => '','country_mailing' => NULL,'address_billing' => '','country_billing' => NULL,'email' => NULL,'phone' => NULL,'legal_form' => NULL,'registration_no' => NULL,'warn' => '0','notes' => 'TEST DATA','VAT_number' => NULL,'creator' => 'phpipuser','updated' => '2019-01-16 16:09:55','updater' => 'root','remember_token' => NULL),
  array('id' => '127','name' => 'BOBLETT Brennan','first_name' => NULL,'display_name' => 'BOBLET','login' => NULL,'password' => NULL,'password_salt' => NULL,'last_login' => NULL,'default_role' => 'INV','function' => NULL,'parent_id' => NULL,'company_id' => '124','site_id' => NULL,'phy_person' => '1','nationality' => 'FR','small_entity' => '0','address' => 'dfghgc','country' => 'US','address_mailing' => 'df','country_mailing' => 'US','address_billing' => 'hjfgkljf','country_billing' => 'US','email' => NULL,'phone' => NULL,'legal_form' => NULL,'registration_no' => NULL,'warn' => '0','notes' => 'TEST DATA','VAT_number' => NULL,'creator' => 'phpipuser','updated' => '2019-02-14 09:01:47','updater' => 'root','remember_token' => NULL),
  array('id' => '128','name' => 'Boehmert & Boehmert','first_name' => NULL,'display_name' => 'Boehmert','login' => NULL,'password' => NULL,'password_salt' => NULL,'last_login' => NULL,'default_role' => 'AGT','function' => 'fonction','parent_id' => NULL,'company_id' => NULL,'site_id' => NULL,'phy_person' => '1','nationality' => 'DE','small_entity' => '1','address' => 'address','country' => 'DE','address_mailing' => 'mailing ad','country_mailing' => 'BE','address_billing' => 'billing','country_billing' => 'FR','email' => 'email','phone' => 'phone','legal_form' => 'sas','registration_no' => 'Siren','warn' => '0','notes' => 'Blabla','VAT_number' => 'Vat no.','creator' => 'phpipuser','updated' => '2018-05-14 15:38:11','updater' => 'root','remember_token' => NULL),
  array('id' => '129','name' => 'SODERBERG Richard','first_name' => NULL,'display_name' => NULL,'login' => 'SR','password' => '$2y$10$jcKMOnHVpl0cciOTfmCAouIrZ/gQCHxu31oSuThcM/k4YXW/0HruC','password_salt' => NULL,'last_login' => NULL,'default_role' => 'CLI','function' => NULL,'parent_id' => NULL,'company_id' => NULL,'site_id' => NULL,'phy_person' => '1','nationality' => NULL,'small_entity' => '0','address' => '','country' => 'US','address_mailing' => '','country_mailing' => NULL,'address_billing' => '','country_billing' => NULL,'email' => 'yves.brungard@gadz.org','phone' => NULL,'legal_form' => NULL,'registration_no' => NULL,'warn' => '0','notes' => NULL,'VAT_number' => NULL,'creator' => 'phpipuser','updated' => '2019-02-09 10:20:59','updater' => 'root','remember_token' => 'feZJKxg5gk4LOtqIJB0cyi80f04pZaNjDvVrVttT0L5nJySowxT7RKygLUjg'),
  array('id' => '130','name' => 'Texas Patents','first_name' => NULL,'display_name' => NULL,'login' => NULL,'password' => NULL,'password_salt' => NULL,'last_login' => NULL,'default_role' => 'AGT','function' => NULL,'parent_id' => NULL,'company_id' => NULL,'site_id' => NULL,'phy_person' => '1','nationality' => NULL,'small_entity' => '0','address' => '','country' => 'US','address_mailing' => '','country_mailing' => NULL,'address_billing' => '','country_billing' => NULL,'email' => NULL,'phone' => NULL,'legal_form' => NULL,'registration_no' => NULL,'warn' => '0','notes' => NULL,'VAT_number' => NULL,'creator' => 'phpipuser','updated' => '2017-12-03 17:37:19','updater' => NULL,'remember_token' => NULL)
);
