<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 4.6.6deb5
 */

/**
 * Database `phpip`
 */

/* `phpip`.`actor` */
$actor = array(
  array('ID' => '124','name' => 'Tesla Motors Inc.','first_name' => NULL,'display_name' => 'Tesla','login' => NULL,'password' => NULL,'password_salt' => NULL,'last_login' => NULL,'default_role' => 'CLI','function' => NULL,'parent_ID' => NULL,'company_ID' => NULL,'site_ID' => NULL,'phy_person' => '0','nationality' => NULL,'small_entity' => '0','address' => '','country' => NULL,'address_mailing' => '','country_mailing' => NULL,'address_billing' => '','country_billing' => NULL,'email' => NULL,'phone' => NULL,'legal_form' => NULL,'registration_no' => NULL,'warn' => '0','notes' => 'TEST DATA','VAT_number' => NULL,'creator' => 'phpipuser','updated' => '2017-12-03 16:45:57','updater' => 'phpipuser'),
  array('ID' => '125','name' => 'BAGLINO Andrew D.','first_name' => NULL,'display_name' => NULL,'login' => NULL,'password' => NULL,'password_salt' => NULL,'last_login' => NULL,'default_role' => 'INV','function' => NULL,'parent_ID' => NULL,'company_ID' => '124','site_ID' => NULL,'phy_person' => '1','nationality' => NULL,'small_entity' => '0','address' => '','country' => 'US','address_mailing' => '','country_mailing' => NULL,'address_billing' => '','country_billing' => NULL,'email' => NULL,'phone' => NULL,'legal_form' => NULL,'registration_no' => NULL,'warn' => '0','notes' => 'TEST DATA','VAT_number' => NULL,'creator' => 'phpipuser','updated' => '2017-12-03 16:45:48','updater' => 'phpipuser'),
  array('ID' => '126','name' => 'HAYER Thorsten','first_name' => NULL,'display_name' => NULL,'login' => NULL,'password' => NULL,'password_salt' => NULL,'last_login' => NULL,'default_role' => 'INV','function' => NULL,'parent_ID' => NULL,'company_ID' => '124','site_ID' => NULL,'phy_person' => '1','nationality' => NULL,'small_entity' => '0','address' => '','country' => NULL,'address_mailing' => '','country_mailing' => NULL,'address_billing' => '','country_billing' => NULL,'email' => NULL,'phone' => NULL,'legal_form' => NULL,'registration_no' => NULL,'warn' => '0','notes' => 'TEST DATA','VAT_number' => NULL,'creator' => 'phpipuser','updated' => '2017-12-03 16:45:37','updater' => 'phpipuser'),
  array('ID' => '127','name' => 'BOBLETT Brennan','first_name' => NULL,'display_name' => NULL,'login' => NULL,'password' => NULL,'password_salt' => NULL,'last_login' => NULL,'default_role' => 'INV','function' => NULL,'parent_ID' => NULL,'company_ID' => '124','site_ID' => NULL,'phy_person' => '1','nationality' => NULL,'small_entity' => '0','address' => '','country' => 'US','address_mailing' => '','country_mailing' => NULL,'address_billing' => '','country_billing' => NULL,'email' => NULL,'phone' => NULL,'legal_form' => NULL,'registration_no' => NULL,'warn' => '0','notes' => 'TEST DATA','VAT_number' => NULL,'creator' => 'phpipuser','updated' => '2017-12-03 16:45:23','updater' => NULL),
  array('ID' => '128','name' => 'Boehmert & Boehmert','first_name' => NULL,'display_name' => 'Boehmert','login' => NULL,'password' => NULL,'password_salt' => NULL,'last_login' => NULL,'default_role' => 'AGT','function' => NULL,'parent_ID' => NULL,'company_ID' => NULL,'site_ID' => NULL,'phy_person' => '1','nationality' => 'DE','small_entity' => '0','address' => '','country' => 'DE','address_mailing' => '','country_mailing' => NULL,'address_billing' => '','country_billing' => NULL,'email' => NULL,'phone' => NULL,'legal_form' => NULL,'registration_no' => NULL,'warn' => '0','notes' => NULL,'VAT_number' => NULL,'creator' => 'phpipuser','updated' => '2017-12-03 17:40:13','updater' => 'phpipuser'),
  array('ID' => '129','name' => 'SODERBERG Richard','first_name' => NULL,'display_name' => NULL,'login' => NULL,'password' => NULL,'password_salt' => NULL,'last_login' => NULL,'default_role' => 'AGT','function' => NULL,'parent_ID' => NULL,'company_ID' => NULL,'site_ID' => NULL,'phy_person' => '1','nationality' => NULL,'small_entity' => '0','address' => '','country' => 'US','address_mailing' => '','country_mailing' => NULL,'address_billing' => '','country_billing' => NULL,'email' => NULL,'phone' => NULL,'legal_form' => NULL,'registration_no' => NULL,'warn' => '0','notes' => NULL,'VAT_number' => NULL,'creator' => 'phpipuser','updated' => '2017-12-03 17:33:37','updater' => NULL),
  array('ID' => '130','name' => 'Texas Patents','first_name' => NULL,'display_name' => NULL,'login' => NULL,'password' => NULL,'password_salt' => NULL,'last_login' => NULL,'default_role' => 'AGT','function' => NULL,'parent_ID' => NULL,'company_ID' => NULL,'site_ID' => NULL,'phy_person' => '1','nationality' => NULL,'small_entity' => '0','address' => '','country' => 'US','address_mailing' => '','country_mailing' => NULL,'address_billing' => '','country_billing' => NULL,'email' => NULL,'phone' => NULL,'legal_form' => NULL,'registration_no' => NULL,'warn' => '0','notes' => NULL,'VAT_number' => NULL,'creator' => 'phpipuser','updated' => '2017-12-03 17:37:19','updater' => NULL)
);
