<?php
$event_name = array(
  array('code' => 'ABA','name' => 'Abandoned','is_task' => '0','status_event' => '1','use_matter_resp' => '0','unique' => '1','uqtrigger' => '0','killer' => '1'),
  array('code' => 'ABO','name' => 'Abandon Original','category' => 'PAT','country' => 'EP','is_task' => '1','status_event' => '0','use_matter_resp' => '0','unique' => '1','uqtrigger' => '0','killer' => '0','notes' => 'Abandon the originating patent that was re-designated in EP'),
  array('code' => 'ADV','name' => 'Advisory Action','category' => 'PAT','country' => 'US','is_task' => '0','status_event' => '0','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '0'),
  array('code' => 'ALL','name' => 'Allowance','category' => 'PAT','is_task' => '0','status_event' => '1','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '0','notes' => 'Use also for R71.3 in EP'),
  array('code' => 'APL','name' => 'Appeal','is_task' => '0','status_event' => '1','use_matter_resp' => '1','unique' => '0','uqtrigger' => '0','killer' => '0','notes' => 'Appeal or other remedy filed'),
  array('code' => 'CAN','name' => 'Cancelled','category' => 'TM','is_task' => '0','status_event' => '1','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '1'),
  array('code' => 'CLO','name' => 'Closed','category' => 'LTG','is_task' => '0','status_event' => '1','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '1'),
  array('code' => 'COM','name' => 'Communication','is_task' => '0','status_event' => '0','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '0','notes' => 'Communication regarding administrative or formal matters (missing parts, irregularities...)'),
  array('code' => 'CRE','name' => 'Created','is_task' => '0','status_event' => '0','use_matter_resp' => '0','unique' => '1','uqtrigger' => '0','killer' => '0','notes' => 'Creation date of matter - for attaching tasks necessary before anything else'),
  array('code' => 'DAPL','name' => 'Decision on Appeal','is_task' => '0','status_event' => '0','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '0','notes' => 'State outcome in detail field'),
  array('code' => 'DBY','name' => 'Draft By','category' => 'PAT','is_task' => '1','status_event' => '0','use_matter_resp' => '1','unique' => '0','uqtrigger' => '0','killer' => '0'),
  array('code' => 'DEX','name' => 'Deadline Extended','is_task' => '0','status_event' => '0','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '0','notes' => 'Deadline extension requested'),
  array('code' => 'DPAPL','name' => 'Decision on Pre-Appeal','category' => 'PAT','country' => 'US','is_task' => '0','status_event' => '0','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '0'),
  array('code' => 'DRA','name' => 'Drafted','category' => 'PAT','is_task' => '0','status_event' => '1','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '0'),
  array('code' => 'DW','name' => 'Deemed withrawn','is_task' => '0','status_event' => '1','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '0','notes' => 'Decision needing a reply, such as further processing'),
  array('code' => 'EHK','name' => 'Extend to Hong Kong','category' => 'PAT','country' => 'CN','is_task' => '1','status_event' => '0','use_matter_resp' => '0','unique' => '1','uqtrigger' => '0','killer' => '0'),
  array('code' => 'ENT','name' => 'Entered','category' => 'PAT','is_task' => '0','status_event' => '0','use_matter_resp' => '0','unique' => '1','uqtrigger' => '0','killer' => '0','notes' => 'National entry date from PCT phase'),
  array('code' => 'EOP','name' => 'End of Procedure','category' => 'PAT','is_task' => '0','status_event' => '1','use_matter_resp' => '0','unique' => '1','uqtrigger' => '0','killer' => '1','notes' => 'Indicates end of international phase for PCT'),
  array('code' => 'EXA','name' => 'Examiner Action','is_task' => '0','status_event' => '0','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '0','notes' => 'AKA Office Action, i.e. anything related to substantive examination'),
  array('code' => 'EXAF','name' => 'Examiner Action (Final)','category' => 'PAT','country' => 'US','is_task' => '0','status_event' => '0','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '0'),
  array('code' => 'EXP','name' => 'Expiry','is_task' => '0','status_event' => '1','use_matter_resp' => '0','unique' => '1','uqtrigger' => '0','killer' => '1','notes' => 'Do not use nor change - present for internal functionality'),
  array('code' => 'FAP','name' => 'File Notice of Appeal','is_task' => '1','status_event' => '0','use_matter_resp' => '1','unique' => '0','uqtrigger' => '0','killer' => '0'),
  array('code' => 'FBY','name' => 'File by','is_task' => '1','status_event' => '0','use_matter_resp' => '0','unique' => '1','uqtrigger' => '0','killer' => '0'),
  array('code' => 'FDIV','name' => 'File Divisional','category' => 'PAT','is_task' => '1','status_event' => '0','use_matter_resp' => '0','unique' => '1','uqtrigger' => '0','killer' => '0'),
  array('code' => 'FIL','name' => 'Filed','is_task' => '0','status_event' => '1','use_matter_resp' => '0','unique' => '1','uqtrigger' => '0','killer' => '0'),
  array('code' => 'FOP','name' => 'File Opposition','category' => 'OP','country' => 'EP','is_task' => '1','status_event' => '0','use_matter_resp' => '1','unique' => '1','uqtrigger' => '0','killer' => '0'),
  array('code' => 'FPR','name' => 'Further Processing','category' => 'PAT','is_task' => '1','status_event' => '0','use_matter_resp' => '1','unique' => '0','uqtrigger' => '0','killer' => '0'),
  array('code' => 'FRCE','name' => 'File RCE','category' => 'PAT','country' => 'US','is_task' => '1','status_event' => '0','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '0'),
  array('code' => 'GRT','name' => 'Granted','category' => 'PAT','is_task' => '0','status_event' => '1','use_matter_resp' => '0','unique' => '1','uqtrigger' => '0','killer' => '0'),
  array('code' => 'INV','name' => 'Invalidated','category' => 'TM','country' => 'US','is_task' => '0','status_event' => '1','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '1'),
  array('code' => 'LAP','name' => 'Lapsed','is_task' => '0','status_event' => '1','use_matter_resp' => '0','unique' => '1','uqtrigger' => '0','killer' => '1'),
  array('code' => 'NPH','name' => 'National Phase','category' => 'PAT','country' => 'WO','is_task' => '1','status_event' => '0','use_matter_resp' => '0','unique' => '1','uqtrigger' => '1','killer' => '0'),
  array('code' => 'OPP','name' => 'Opposition','country' => 'EP','is_task' => '0','status_event' => '1','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '0'),
  array('code' => 'OPR','name' => 'Oral Proceedings','category' => 'PAT','country' => 'EP','is_task' => '1','status_event' => '0','use_matter_resp' => '1','unique' => '0','uqtrigger' => '0','killer' => '0'),
  array('code' => 'ORE','name' => 'Opposition rejected','category' => 'PAT','country' => 'EP','is_task' => '0','status_event' => '1','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '0'),
  array('code' => 'PAY','name' => 'Pay','is_task' => '1','status_event' => '0','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '0','notes' => 'Use for any fees to be paid'),
  array('code' => 'PDES','name' => 'Post designation','category' => 'TM','country' => 'WO','is_task' => '0','status_event' => '1','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '0'),
  array('code' => 'PFIL','name' => 'Parent Filed','category' => 'PAT','is_task' => '0','status_event' => '1','use_matter_resp' => '0','unique' => '1','uqtrigger' => '0','killer' => '0','notes' => 'Filing date of the parent (use only when the matter type is defined). Use as link to the parent matter.'),
  array('code' => 'PR','name' => 'Publication of Reg.','category' => 'TM','is_task' => '0','status_event' => '1','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '0'),
  array('code' => 'PREP','name' => 'Prepare','is_task' => '1','status_event' => '0','use_matter_resp' => '1','unique' => '0','uqtrigger' => '0','killer' => '0','notes' => 'Any further action to be done by the responsible (comments, pre-handling, ...)'),
  array('code' => 'PRI','name' => 'Priority Claim','is_task' => '0','status_event' => '1','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '0','notes' => 'Use as link to the priority matter'),
  array('code' => 'PRID','name' => 'Priority Deadline','is_task' => '1','status_event' => '0','use_matter_resp' => '0','unique' => '1','uqtrigger' => '0','killer' => '0'),
  array('code' => 'PROD','name' => 'Produce','is_task' => '1','status_event' => '0','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '0','notes' => 'Any further documents to be filed (inventor designation, priority document, missing parts...)'),
  array('code' => 'PSR','name' => 'Publication of SR','category' => 'PAT','country' => 'EP','is_task' => '0','status_event' => '0','use_matter_resp' => '0','unique' => '1','uqtrigger' => '0','killer' => '0','notes' => 'A3 publication'),
  array('code' => 'PUB','name' => 'Published','is_task' => '0','status_event' => '1','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '0','notes' => 'For EP, this means publication WITH the search report (A1 publ.)'),
  array('code' => 'RCE','name' => 'Request Continued Examination','category' => 'PAT','country' => 'US','is_task' => '0','status_event' => '1','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '0'),
  array('code' => 'REC','name' => 'Received','is_task' => '0','status_event' => '1','use_matter_resp' => '0','unique' => '1','uqtrigger' => '0','killer' => '0','notes' => 'Date the case was received from the client'),
  array('code' => 'REF','name' => 'Refused','is_task' => '0','status_event' => '1','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '0','notes' => 'This is the final decision, that can only be appealed - do not mistake with an exam report'),
  array('code' => 'REG','name' => 'Registration','category' => 'TM','is_task' => '0','status_event' => '1','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '0'),
  array('code' => 'REM','name' => 'Reminder','is_task' => '1','status_event' => '0','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '0'),
  array('code' => 'REN','name' => 'Renewal','is_task' => '1','status_event' => '0','use_matter_resp' => '0','unique' => '0','uqtrigger' => '1','killer' => '0','notes' => 'AKA Annuity'),
  array('code' => 'REP','name' => 'Respond','is_task' => '1','status_event' => '0','use_matter_resp' => '1','unique' => '0','uqtrigger' => '0','killer' => '0','notes' => 'Use for any response'),
  array('code' => 'REQ','name' => 'Request Examination','is_task' => '1','status_event' => '0','use_matter_resp' => '0','unique' => '1','uqtrigger' => '0','killer' => '0'),
  array('code' => 'RSTR','name' => 'Restriction Req.','category' => 'PAT','country' => 'US','is_task' => '0','status_event' => '0','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '0'),
  array('code' => 'SOL','name' => 'Sold','is_task' => '0','status_event' => '1','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '1'),
  array('code' => 'SOP','name' => 'Summons to Oral Proc.','is_task' => '0','status_event' => '0','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '0'),
  array('code' => 'SR','name' => 'Search Report','is_task' => '0','status_event' => '0','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '0'),
  array('code' => 'SUS','name' => 'Suspended','is_task' => '0','status_event' => '1','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '0'),
  array('code' => 'TRF','name' => 'Transferred','is_task' => '0','status_event' => '1','use_matter_resp' => '0','unique' => '1','uqtrigger' => '0','killer' => '1','notes' => 'Case no longer followed'),
  array('code' => 'VAL','name' => 'Validate','category' => 'PAT','country' => 'EP','is_task' => '1','status_event' => '0','use_matter_resp' => '0','unique' => '1','uqtrigger' => '0','killer' => '0','notes' => 'Validate granted EP in designated countries'),
  array('code' => 'WAT','name' => 'Watch','is_task' => '1','status_event' => '0','use_matter_resp' => '1','unique' => '0','uqtrigger' => '0','killer' => '0'),
  array('code' => 'WIT','name' => 'Withdrawal','category' => 'PAT','is_task' => '0','status_event' => '1','use_matter_resp' => '0','unique' => '0','uqtrigger' => '0','killer' => '1')
);
