<?php
$task_rules = array(
  array('id' => '1','active' => '1','task' => 'PRID','trigger_event' => 'FIL','for_category' => 'PAT','months' => '12','abort_on' => 'PRI','use_parent' => '1','use_priority' => '1','notes' => 'Priority deadline is inserted only if no priority event exists'),
  array('id' => '2','active' => '1','task' => 'PRID','trigger_event' => 'FIL','for_category' => 'TM','months' => '6','abort_on' => 'PRI','notes' => 'Priority deadline is inserted only if no priority event exists'),
  array('id' => '3','active' => '1','task' => 'FBY','trigger_event' => 'FIL','clear_task' => '1','for_category' => 'PAT','notes' => 'Clear "File by" task when "Filed" event is created'),
  array('id' => '4','active' => '1','task' => 'PRID','trigger_event' => 'FIL','for_category' => 'PRO','months' => '12'),
  array('id' => '5','active' => '1','task' => 'DBY','trigger_event' => 'DRA','clear_task' => '1','for_category' => 'PAT','for_country' => 'FR','for_origin' => 'BE','detail' => '2','responsible' => 'phpipuser','notes' => 'Clear "Draft by" task when "Drafted" event is created'),
  array('id' => '6','active' => '1','task' => 'REQ','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'JP','years' => '3','abort_on' => 'EXA'),
  array('id' => '7','active' => '1','task' => 'REQ','trigger_event' => 'PUB','for_category' => 'PAT','for_country' => 'EP','months' => '6','abort_on' => 'EXA'),
  array('id' => '8','active' => '1','task' => 'EXP','trigger_event' => 'FIL','for_category' => 'PRO','months' => '12'),
  array('id' => '9','active' => '1','task' => 'REP','trigger_event' => 'SR','for_category' => 'PAT','for_country' => 'FR','detail' => 'Search Report','months' => '3','abort_on' => 'GRT'),
  array('id' => '10','active' => '1','task' => 'REP','trigger_event' => 'EXA','for_category' => 'PAT','for_country' => 'US','detail' => 'Exam Report','months' => '3','abort_on' => 'GRT'),
  array('id' => '11','active' => '1','task' => 'REP','trigger_event' => 'EXA','for_category' => 'PAT','for_country' => 'EP','detail' => 'Exam Report','months' => '4','abort_on' => 'GRT'),
  array('id' => '12','active' => '1','task' => 'EXP','trigger_event' => 'FIL','for_category' => 'PAT','years' => '20','use_parent' => '1'),
  array('id' => '13','active' => '1','task' => 'REP','trigger_event' => 'ALL','for_category' => 'PAT','for_country' => 'EP','detail' => 'R71(3)','months' => '4','abort_on' => 'GRT'),
  array('id' => '14','active' => '1','task' => 'PAY','trigger_event' => 'ALL','for_category' => 'PAT','for_country' => 'EP','detail' => 'Grant Fee','months' => '4','abort_on' => 'GRT'),
  array('id' => '15','active' => '1','task' => 'PROD','trigger_event' => 'ALL','for_category' => 'PAT','for_country' => 'EP','detail' => 'Claim Translation','months' => '4','abort_on' => 'GRT'),
  array('id' => '16','active' => '1','task' => 'VAL','trigger_event' => 'GRT','for_category' => 'PAT','for_country' => 'EP','detail' => 'Translate where necessary','months' => '3'),
  array('id' => '18','active' => '1','task' => 'REP','trigger_event' => 'PUB','for_category' => 'PAT','for_country' => 'EP','detail' => 'Written Opinion','months' => '6','abort_on' => 'EXA'),
  array('id' => '19','active' => '1','task' => 'PAY','trigger_event' => 'PUB','for_category' => 'PAT','for_country' => 'EP','detail' => 'Designation Fees','months' => '6','abort_on' => 'EXA'),
  array('id' => '20','active' => '1','task' => 'PROD','trigger_event' => 'PRI','for_category' => 'PAT','for_country' => 'US','detail' => 'Decl. and Assignment','months' => '12'),
  array('id' => '21','active' => '1','task' => 'FBY','trigger_event' => 'PRI','for_category' => 'PAT','detail' => 'Priority Deadline','months' => '12','abort_on' => 'FIL'),
  array('id' => '22','active' => '1','task' => 'NPH','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'WO','months' => '30','use_priority' => '1'),
  array('id' => '23','active' => '1','task' => 'REQ','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'WO','months' => '22','abort_on' => 'EXA','use_priority' => '1'),
  array('id' => '24','active' => '1','task' => 'DBY','trigger_event' => 'REC','for_category' => 'PAT','for_country' => 'FR','months' => '2','abort_on' => 'PRI'),
  array('id' => '25','active' => '1','task' => 'PRID','trigger_event' => 'PRI','delete_task' => '1','for_category' => 'PAT','condition_event' => 'FIL','notes' => 'Deletes priority deadline when a priority event is inserted'),
  array('id' => '26','active' => '1','task' => 'EHK','trigger_event' => 'PUB','for_category' => 'PAT','for_country' => 'CN','months' => '6'),
  array('id' => '27','active' => '1','task' => 'FOP','trigger_event' => 'GRT','for_category' => 'OP','for_country' => 'EP','months' => '9'),
  array('id' => '29','active' => '1','task' => 'DBY','trigger_event' => 'FIL','clear_task' => '1','for_category' => 'PAT'),
  array('id' => '30','active' => '1','task' => 'PROD','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'US','detail' => 'IDS','months' => '2'),
  array('id' => '32','active' => '1','task' => 'REP','trigger_event' => 'EXA','for_category' => 'PAT','for_country' => 'WO','months' => '3'),
  array('id' => '33','active' => '1','task' => 'EXP','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'WO','months' => '31','use_priority' => '1'),
  array('id' => '34','active' => '1','task' => 'REM','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'WO','detail' => 'National Phase','months' => '27','use_priority' => '1'),
  array('id' => '35','active' => '1','task' => 'PROD','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'FR','detail' => 'Small Entity','months' => '1','abort_on' => 'PRI','use_parent' => '1'),
  array('id' => '36','active' => '1','task' => 'PAY','trigger_event' => 'GRT','for_category' => 'PAT','for_country' => 'CN','detail' => 'HK Grant Fee','months' => '6'),
  array('id' => '37','active' => '1','task' => 'REP','trigger_event' => 'COM','for_category' => 'PAT','detail' => 'Communication','months' => '2'),
  array('id' => '38','active' => '1','task' => 'FOP','trigger_event' => 'OPP','clear_task' => '1','for_category' => 'OP','for_country' => 'EP','notes' => 'Clear "File Opposition" task when "Opposition" event is created'),
  array('id' => '39','active' => '1','task' => 'PAY','trigger_event' => 'ALL','for_category' => 'PAT','for_country' => 'JP','detail' => 'Grant Fee','months' => '1'),
  array('id' => '40','active' => '1','task' => 'FPR','trigger_event' => 'DW','for_category' => 'PAT','for_country' => 'EP','months' => '2'),
  array('id' => '41','active' => '1','task' => 'REP','trigger_event' => 'PSR','for_category' => 'PAT','for_country' => 'EP','detail' => 'R70(2)','months' => '6'),
  array('id' => '42','active' => '1','task' => 'NPH','trigger_event' => 'PRI','for_category' => 'PAT','for_origin' => 'WO','months' => '30'),
  array('id' => '43','active' => '1','task' => 'PAY','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'FR','detail' => 'Filing Fee','months' => '1'),
  array('id' => '44','active' => '1','task' => 'PAY','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'EP','detail' => 'Filing Fee','months' => '1'),
  array('id' => '45','active' => '1','task' => 'VAL','trigger_event' => 'GRT','for_category' => 'PAT','for_origin' => 'EP','months' => '3'),
  array('id' => '46','active' => '1','task' => 'REP','trigger_event' => 'RSTR','for_category' => 'PAT','for_country' => 'US','detail' => 'Restriction Req.','months' => '1'),
  array('id' => '47','active' => '1','task' => 'REP','trigger_event' => 'COM','for_category' => 'PAT','for_country' => 'EP','detail' => 'R161','months' => '6'),
  array('id' => '48','active' => '1','task' => 'FAP','trigger_event' => 'REF','for_category' => 'PAT','months' => '2'),
  array('id' => '49','active' => '1','task' => 'PROD','trigger_event' => 'APL','for_category' => 'PAT','detail' => 'Appeal Brief','months' => '2'),
  array('id' => '52','active' => '1','task' => 'REP','trigger_event' => 'COM','for_category' => 'OP','for_country' => 'EP','detail' => 'Observations','months' => '4'),
  array('id' => '53','active' => '1','task' => 'REQ','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'KR','years' => '3','abort_on' => 'EXA'),
  array('id' => '54','active' => '1','task' => 'REQ','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'CA','years' => '5','abort_on' => 'EXA'),
  array('id' => '55','active' => '1','task' => 'REQ','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'CN','years' => '3','abort_on' => 'EXA','use_priority' => '1'),
  array('id' => '56','active' => '1','task' => 'PAY','trigger_event' => 'ALL','for_category' => 'PAT','for_country' => 'CA','detail' => 'Grant Fee','months' => '6'),
  array('id' => '57','active' => '1','task' => 'PROD','trigger_event' => 'PRI','for_category' => 'PAT','detail' => 'Priority Docs','months' => '16'),
  array('id' => '58','active' => '1','task' => 'PAY','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'WO','detail' => 'Filing Fee','months' => '1'),
  array('id' => '60','active' => '1','task' => 'REM','trigger_event' => 'ALL','for_category' => 'PAT','for_country' => 'US','detail' => 'File divisional','months' => '1','condition_event' => 'RSTR'),
  array('id' => '61','active' => '1','task' => 'REP','trigger_event' => 'EXA','for_category' => 'PAT','for_country' => 'CN','detail' => 'Exam Report','months' => '4'),
  array('id' => '62','active' => '1','task' => 'REP','trigger_event' => 'EXA','for_category' => 'PAT','for_country' => 'CA','detail' => 'Exam Report','months' => '6'),
  array('id' => '63','active' => '1','task' => 'REM','trigger_event' => 'SR','for_category' => 'PAT','for_country' => 'FR','detail' => 'Request extension','months' => '3'),
  array('id' => '64','active' => '1','task' => 'REM','trigger_event' => 'EXA','for_category' => 'PAT','for_country' => 'EP','detail' => 'Request extension','months' => '4'),
  array('id' => '65','active' => '1','task' => 'FBY','trigger_event' => 'REC','for_category' => 'PAT','months' => '3'),
  array('id' => '66','active' => '1','task' => 'PAY','trigger_event' => 'ALL','for_category' => 'PAT','for_country' => 'FR','detail' => 'Grant Fee','months' => '2'),
  array('id' => '67','active' => '1','task' => 'REQ','trigger_event' => 'PSR','for_category' => 'PAT','for_country' => 'EP','months' => '6','abort_on' => 'EXA'),
  array('id' => '68','active' => '1','task' => 'PAY','trigger_event' => 'PSR','for_category' => 'PAT','for_country' => 'EP','detail' => 'Designation Fees','months' => '6','abort_on' => 'EXA'),
  array('id' => '69','active' => '1','task' => 'REP','trigger_event' => 'PSR','for_category' => 'PAT','for_country' => 'EP','detail' => 'Written Opinion','months' => '6','abort_on' => 'EXA'),
  array('id' => '70','active' => '1','task' => 'REQ','trigger_event' => 'PRI','for_category' => 'PAT','for_country' => 'IN','months' => '48'),
  array('id' => '102','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'FR','detail' => '2','years' => '1','end_of_month' => '1','use_parent' => '1','cost' => '38.00','fee' => NULL),
  array('id' => '103','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'FR','detail' => '3','years' => '2','end_of_month' => '1','use_parent' => '1','cost' => '38.00','fee' => NULL),
  array('id' => '104','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'FR','detail' => '4','years' => '3','end_of_month' => '1','use_parent' => '1','cost' => '38.00','fee' => NULL),
  array('id' => '105','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'FR','detail' => '5','years' => '4','end_of_month' => '1','use_parent' => '1','cost' => '38.00','fee' => NULL),
  array('id' => '106','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'FR','detail' => '6','years' => '5','end_of_month' => '1','use_parent' => '1','cost' => '76.00','fee' => NULL),
  array('id' => '107','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'FR','detail' => '7','years' => '6','end_of_month' => '1','use_parent' => '1','cost' => '96.00','fee' => NULL),
  array('id' => '108','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'FR','detail' => '8','years' => '7','end_of_month' => '1','use_parent' => '1','cost' => '136.00','fee' => NULL),
  array('id' => '109','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'FR','detail' => '9','years' => '8','end_of_month' => '1','use_parent' => '1','cost' => '180.00','fee' => NULL),
  array('id' => '110','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'FR','detail' => '10','years' => '9','end_of_month' => '1','use_parent' => '1','cost' => '220.00','fee' => NULL),
  array('id' => '111','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'FR','detail' => '11','years' => '10','end_of_month' => '1','use_parent' => '1','cost' => '260.00','fee' => NULL),
  array('id' => '112','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'FR','detail' => '12','years' => '11','end_of_month' => '1','use_parent' => '1','cost' => '300.00','fee' => NULL),
  array('id' => '113','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'FR','detail' => '13','years' => '12','end_of_month' => '1','use_parent' => '1','cost' => '350.00','fee' => NULL),
  array('id' => '114','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'FR','detail' => '14','years' => '13','end_of_month' => '1','use_parent' => '1','cost' => '400.00','fee' => NULL),
  array('id' => '115','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'FR','detail' => '15','years' => '14','end_of_month' => '1','use_parent' => '1','cost' => '450.00','fee' => NULL),
  array('id' => '116','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'FR','detail' => '16','years' => '15','end_of_month' => '1','use_parent' => '1','cost' => '510.00','fee' => NULL),
  array('id' => '117','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'FR','detail' => '17','years' => '16','end_of_month' => '1','use_parent' => '1','cost' => '570.00','fee' => NULL),
  array('id' => '118','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'FR','detail' => '18','years' => '17','end_of_month' => '1','use_parent' => '1','cost' => '640.00','fee' => NULL),
  array('id' => '119','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'FR','detail' => '19','years' => '18','end_of_month' => '1','use_parent' => '1','cost' => '720.00','fee' => NULL),
  array('id' => '120','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'FR','detail' => '20','years' => '19','end_of_month' => '1','use_parent' => '1','cost' => '790.00','fee' => NULL),
  array('id' => '203','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'EP','detail' => '3','years' => '2','end_of_month' => '1','use_parent' => '1','cost' => '465.00','fee' => NULL),
  array('id' => '204','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'EP','detail' => '4','years' => '3','end_of_month' => '1','use_parent' => '1','cost' => '580.00','fee' => NULL),
  array('id' => '205','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'EP','detail' => '5','years' => '4','end_of_month' => '1','use_parent' => '1','cost' => '810.00','fee' => NULL),
  array('id' => '206','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'EP','detail' => '6','years' => '5','end_of_month' => '1','use_parent' => '1','cost' => '1040.00','fee' => NULL),
  array('id' => '207','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'EP','detail' => '7','years' => '6','end_of_month' => '1','use_parent' => '1','cost' => '1155.00','fee' => NULL),
  array('id' => '208','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'EP','detail' => '8','years' => '7','end_of_month' => '1','use_parent' => '1','cost' => '1265.00','fee' => NULL),
  array('id' => '209','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'EP','detail' => '9','years' => '8','end_of_month' => '1','use_parent' => '1','cost' => '1380.00','fee' => NULL),
  array('id' => '210','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'EP','detail' => '10','years' => '9','end_of_month' => '1','use_parent' => '1','cost' => '1560.00','fee' => NULL),
  array('id' => '211','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'EP','detail' => '11','years' => '10','end_of_month' => '1','use_parent' => '1','cost' => '1560.00','fee' => NULL),
  array('id' => '212','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'EP','detail' => '12','years' => '11','end_of_month' => '1','use_parent' => '1','cost' => '1560.00','fee' => NULL),
  array('id' => '213','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'EP','detail' => '13','years' => '12','end_of_month' => '1','use_parent' => '1','cost' => '1560.00','fee' => NULL),
  array('id' => '214','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'EP','detail' => '14','years' => '13','end_of_month' => '1','use_parent' => '1','cost' => '1560.00','fee' => NULL),
  array('id' => '215','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'EP','detail' => '15','years' => '14','end_of_month' => '1','use_parent' => '1','cost' => '1560.00','fee' => NULL),
  array('id' => '216','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'EP','detail' => '16','years' => '15','end_of_month' => '1','use_parent' => '1','cost' => '1560.00','fee' => NULL),
  array('id' => '217','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'EP','detail' => '17','years' => '16','end_of_month' => '1','use_parent' => '1','cost' => '1560.00','fee' => NULL),
  array('id' => '218','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'EP','detail' => '18','years' => '17','end_of_month' => '1','use_parent' => '1','cost' => '1560.00','fee' => NULL),
  array('id' => '219','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'EP','detail' => '19','years' => '18','end_of_month' => '1','use_parent' => '1','cost' => '1560.00','fee' => NULL),
  array('id' => '220','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'EP','detail' => '20','years' => '19','end_of_month' => '1','use_parent' => '1','cost' => '1560.00','fee' => NULL),
  array('id' => '234','active' => '1','task' => 'PAY','trigger_event' => 'ALL','for_category' => 'PAT','for_country' => 'CN','detail' => 'Grant Fee','days' => '76'),
  array('id' => '235','active' => '1','task' => 'REP','trigger_event' => 'SR','for_category' => 'PAT','for_country' => 'WO','detail' => 'Written Opinion','months' => '3'),
  array('id' => '236','active' => '1','task' => 'PAY','trigger_event' => 'ALL','for_category' => 'PAT','for_country' => 'US','detail' => 'Grant Fee','months' => '3'),
  array('id' => '237','active' => '1','task' => 'PROD','trigger_event' => 'GRT','for_category' => 'PAT','for_country' => 'IN','detail' => 'Working Report','months' => '2','end_of_month' => '1','notes' => 'Change date to end of March'),
  array('id' => '238','active' => '1','task' => 'WAT','trigger_event' => 'PUB','for_category' => 'TM','for_country' => 'FR','detail' => 'Opposition deadline','months' => '2'),
  array('id' => '239','active' => '1','task' => 'WAT','trigger_event' => 'PUB','for_category' => 'TM','for_country' => 'EM','detail' => 'Opposition deadline','months' => '3'),
  array('id' => '240','active' => '1','task' => 'WAT','trigger_event' => 'PUB','for_category' => 'TM','for_country' => 'US','detail' => 'Opposition deadline','days' => '30'),
  array('id' => '242','active' => '1','task' => 'PROD','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'US','detail' => 'Declaration of use','months' => '66','notes' => 'délai à 5 ans et demi'),
  array('id' => '1001','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'TM','detail' => '10','years' => '10'),
  array('id' => '1002','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'TM','detail' => '20','years' => '20'),
  array('id' => '1003','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'TM','detail' => '30','years' => '30'),
  array('id' => '1004','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'TM','detail' => '40','years' => '40'),
  array('id' => '1005','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'TM','detail' => '50','years' => '50'),
  array('id' => '1011','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'CA','detail' => '15','years' => '15'),
  array('id' => '1012','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'CA','detail' => '30','years' => '30'),
  array('id' => '1013','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'CA','detail' => '45','years' => '45'),
  array('id' => '1081','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'US','detail' => '10','years' => '10'),
  array('id' => '1082','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'US','detail' => '20','years' => '20'),
  array('id' => '1083','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'US','detail' => '30','years' => '30'),
  array('id' => '1084','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'US','detail' => '40','years' => '40'),
  array('id' => '1085','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'US','detail' => '50','years' => '50'),
  array('id' => '1091','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'JP','detail' => '10','years' => '10'),
  array('id' => '1092','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'JP','detail' => '20','years' => '20'),
  array('id' => '1093','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'JP','detail' => '30','years' => '30'),
  array('id' => '1094','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'JP','detail' => '40','years' => '40'),
  array('id' => '1101','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'KR','detail' => '10','years' => '10'),
  array('id' => '1102','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'KR','detail' => '20','years' => '20'),
  array('id' => '1103','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'KR','detail' => '30','years' => '30'),
  array('id' => '1104','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'KR','detail' => '40','years' => '40'),
  array('id' => '1121','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'BR','detail' => '10','years' => '10'),
  array('id' => '1122','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'BR','detail' => '20','years' => '20'),
  array('id' => '1123','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'BR','detail' => '30','years' => '30'),
  array('id' => '1124','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'BR','detail' => '40','years' => '40'),
  array('id' => '1131','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'CN','detail' => '10','years' => '10'),
  array('id' => '1132','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'CN','detail' => '20','years' => '20'),
  array('id' => '1133','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'CN','detail' => '30','years' => '30'),
  array('id' => '1134','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'CN','detail' => '40','years' => '40'),
  array('id' => '1181','active' => '1','task' => 'PROD','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'IN','detail' => 'Annexure to Form 3','years' => '2'),
  array('id' => '1182','active' => '1','task' => 'PROD','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'IN','detail' => 'Declaration','years' => '2'),
  array('id' => '1183','active' => '1','task' => 'PROD','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'IN','detail' => 'Power','years' => '2'),
  array('id' => '1184','active' => '1','task' => 'PAY','trigger_event' => 'ALL','for_category' => 'PAT','for_country' => 'KR','detail' => 'Grant Fee','months' => '3','abort_on' => 'GRT'),
  array('id' => '1185','active' => '1','task' => 'PAY','trigger_event' => 'ALL','for_category' => 'PAT','for_country' => 'TW','detail' => 'Grant Fee','months' => '3'),
  array('id' => '1186','active' => '1','task' => 'REP','trigger_event' => 'EXA','for_category' => 'PAT','for_country' => 'AU','detail' => 'Exam Report','months' => '12'),
  array('id' => '1187','active' => '1','task' => 'REP','trigger_event' => 'EXA','for_category' => 'PAT','for_country' => 'IN','detail' => 'Exam Report','months' => '6'),
  array('id' => '1188','active' => '1','task' => 'REP','trigger_event' => 'EXA','for_category' => 'PAT','for_country' => 'KR','detail' => 'Exam Report','months' => '2'),
  array('id' => '1189','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'DSG','for_country' => 'FR','detail' => '1','years' => '5'),
  array('id' => '1190','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'DSG','for_country' => 'FR','detail' => '2','years' => '10'),
  array('id' => '1191','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'DSG','for_country' => 'FR','detail' => '3','years' => '15'),
  array('id' => '1192','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'DSG','for_country' => 'FR','detail' => '4','years' => '20'),
  array('id' => '1193','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'DSG','for_country' => 'FR','detail' => '5','years' => '25'),
  array('id' => '1194','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'DSG','for_country' => 'EM','detail' => '1','years' => '5'),
  array('id' => '1195','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'DSG','for_country' => 'EM','detail' => '2','years' => '10'),
  array('id' => '1196','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'DSG','for_country' => 'EM','detail' => '3','years' => '15'),
  array('id' => '1197','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'DSG','for_country' => 'EM','detail' => '4','years' => '20'),
  array('id' => '1198','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'DSG','for_country' => 'EM','detail' => '5','years' => '25'),
  array('id' => '1211','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'DK','detail' => '10','years' => '10'),
  array('id' => '1212','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'DK','detail' => '20','years' => '20'),
  array('id' => '1213','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'DK','detail' => '30','years' => '30'),
  array('id' => '1214','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'DK','detail' => '40','years' => '40'),
  array('id' => '1215','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'DK','detail' => '50','years' => '50'),
  array('id' => '1216','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'NO','detail' => '10','years' => '10'),
  array('id' => '1217','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'NO','detail' => '20','years' => '20'),
  array('id' => '1218','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'NO','detail' => '30','years' => '30'),
  array('id' => '1219','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'NO','detail' => '40','years' => '40'),
  array('id' => '1220','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'NO','detail' => '50','years' => '50'),
  array('id' => '1221','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'FI','detail' => '10','years' => '10'),
  array('id' => '1222','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'FI','detail' => '20','years' => '20'),
  array('id' => '1223','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'FI','detail' => '30','years' => '30'),
  array('id' => '1224','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'FI','detail' => '40','years' => '40'),
  array('id' => '1225','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'FI','detail' => '50','years' => '50'),
  array('id' => '1228','active' => '1','task' => 'REP','trigger_event' => 'EXA','for_category' => 'PAT','for_country' => 'TW','detail' => 'Exam Report','months' => '3'),
  array('id' => '1230','active' => '1','task' => 'REN','trigger_event' => 'PR','for_category' => 'TM','for_country' => 'TW','detail' => '10','months' => '11','years' => '9','end_of_month' => '1'),
  array('id' => '1231','active' => '1','task' => 'REN','trigger_event' => 'PR','for_category' => 'TM','for_country' => 'TW','detail' => '20','months' => '11','years' => '19','end_of_month' => '1'),
  array('id' => '1232','active' => '1','task' => 'REN','trigger_event' => 'PR','for_category' => 'TM','for_country' => 'TW','detail' => '30','months' => '11','years' => '29','end_of_month' => '1'),
  array('id' => '1233','active' => '1','task' => 'REN','trigger_event' => 'PR','for_category' => 'TM','for_country' => 'TW','detail' => '40','months' => '11','years' => '39','end_of_month' => '1'),
  array('id' => '1234','active' => '1','task' => 'REN','trigger_event' => 'PR','for_category' => 'TM','for_country' => 'TW','detail' => '50','months' => '11','years' => '49','end_of_month' => '1'),
  array('id' => '1235','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'TM','for_country' => 'SA','detail' => '10','months' => '8','years' => '9','notes' => '10 ans Hegira'),
  array('id' => '1236','active' => '1','task' => 'REP','trigger_event' => 'EXA','for_category' => 'PAT','for_country' => 'JP','detail' => 'Exam Report','months' => '3'),
  array('id' => '1237','active' => '1','task' => 'REP','trigger_event' => 'EXA','for_category' => 'TM','for_country' => 'US','detail' => 'Exam Report','months' => '6'),
  array('id' => '1238','active' => '1','task' => 'REP','trigger_event' => 'EXA','for_category' => 'TM','for_country' => 'KR','detail' => 'Exam Report','months' => '2'),
  array('id' => '1239','active' => '1','task' => 'REP','trigger_event' => 'COM','for_category' => 'TM','for_country' => 'EM','detail' => 'Irregularity','months' => '2'),
  array('id' => '1240','active' => '1','task' => 'REP','trigger_event' => 'EXA','for_category' => 'TM','for_country' => 'CN','detail' => 'Exam Report','months' => '1'),
  array('id' => '1241','active' => '1','task' => 'PAY','trigger_event' => 'ALL','for_category' => 'TM','for_country' => 'CA','detail' => 'Grant Fee','months' => '6'),
  array('id' => '1242','active' => '1','task' => 'PROD','trigger_event' => 'ALL','for_category' => 'TM','for_country' => 'CA','detail' => 'Declaration of use','months' => '6'),
  array('id' => '1243','active' => '1','task' => 'WAT','trigger_event' => 'PUB','for_category' => 'TM','for_country' => 'BR','detail' => 'Opposition deadline','days' => '60'),
  array('id' => '1244','active' => '1','task' => 'PROD','trigger_event' => 'OPP','for_category' => 'TM','for_country' => 'FR','detail' => 'Observations','months' => '2'),
  array('id' => '1245','active' => '1','task' => 'PROD','trigger_event' => 'ALL','for_category' => 'TM','for_country' => 'US','detail' => 'Statement of use','months' => '6'),
  array('id' => '1246','active' => '1','task' => 'REP','trigger_event' => 'EXA','for_category' => 'TM','for_country' => 'IL','detail' => 'Exam Report','months' => '3'),
  array('id' => '1247','active' => '1','task' => 'PROD','trigger_event' => 'EXA','for_category' => 'TM','for_country' => 'US','detail' => 'POA','months' => '6'),
  array('id' => '1248','active' => '1','task' => 'PROD','trigger_event' => 'EXA','for_category' => 'TM','for_country' => 'KR','detail' => 'POA','months' => '2'),
  array('id' => '1249','active' => '1','task' => 'PROD','trigger_event' => 'EXA','for_category' => 'TM','for_country' => 'CN','detail' => 'POA','months' => '1'),
  array('id' => '1250','active' => '1','task' => 'PROD','trigger_event' => 'EXA','for_category' => 'TM','for_country' => 'IL','detail' => 'POA','months' => '3'),
  array('id' => '1251','active' => '1','task' => 'PROD','trigger_event' => 'REF','for_category' => 'TM','detail' => 'Appeal Brief','days' => '45'),
  array('id' => '1252','active' => '1','task' => 'PROD','trigger_event' => 'REF','for_category' => 'TM','detail' => 'POA','days' => '45'),
  array('id' => '1253','active' => '1','task' => 'REP','trigger_event' => 'EXA','for_category' => 'TM','for_country' => 'CA','detail' => 'Exam Report','months' => '6'),
  array('id' => '1254','active' => '1','task' => 'REP','trigger_event' => 'EXA','for_category' => 'TM','for_country' => 'TH','detail' => 'Exam Report','months' => '2'),
  array('id' => '1258','active' => '1','task' => 'REP','trigger_event' => 'EXAF','for_category' => 'PAT','for_country' => 'US','detail' => 'Final OA','months' => '2'),
  array('id' => '1259','active' => '1','task' => 'PROD','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'US','detail' => 'Declaration of use','months' => '114','notes' => 'délai à 9 ans et demi'),
  array('id' => '1260','active' => '1','task' => 'REP','trigger_event' => 'COM','for_category' => 'TM','for_country' => 'WO','detail' => 'Irregularity','months' => '3'),
  array('id' => '1262','active' => '1','task' => 'PROD','trigger_event' => 'APL','for_category' => 'TM','for_country' => 'EM','detail' => 'Appeal Brief','months' => '4'),
  array('id' => '1263','active' => '1','task' => 'REN','trigger_event' => 'PRI','for_category' => 'TM','for_country' => 'NZ','detail' => '10','years' => '10','condition_event' => 'ALL'),
  array('id' => '1267','active' => '1','task' => 'REN','trigger_event' => 'PRI','for_category' => 'TM','for_country' => 'NZ','detail' => '20','years' => '20','condition_event' => 'ALL'),
  array('id' => '1268','active' => '1','task' => 'REN','trigger_event' => 'PRI','for_category' => 'TM','for_country' => 'NZ','detail' => '30','years' => '30','condition_event' => 'ALL'),
  array('id' => '1269','active' => '1','task' => 'REN','trigger_event' => 'PRI','for_category' => 'TM','for_country' => 'NZ','detail' => '40','years' => '40','condition_event' => 'ALL'),
  array('id' => '1270','active' => '1','task' => 'REN','trigger_event' => 'PRI','for_category' => 'TM','for_country' => 'NZ','detail' => '50','years' => '50','condition_event' => 'ALL'),
  array('id' => '1271','active' => '1','task' => 'REP','trigger_event' => 'COM','for_category' => 'TM','for_country' => 'FR','detail' => 'Irregularity','months' => '1'),
  array('id' => '1272','active' => '1','task' => 'REN','trigger_event' => 'REG','for_category' => 'TM','for_country' => 'LB','detail' => '15','years' => '15'),
  array('id' => '1273','active' => '1','task' => 'REN','trigger_event' => 'PRI','for_category' => 'TM','for_country' => 'RU','detail' => '10','years' => '10'),
  array('id' => '1274','active' => '1','task' => 'REN','trigger_event' => 'PRI','for_category' => 'TM','for_country' => 'RU','detail' => '20','years' => '20'),
  array('id' => '1275','active' => '1','task' => 'REN','trigger_event' => 'PRI','for_category' => 'TM','for_country' => 'RU','detail' => '30','years' => '30'),
  array('id' => '1277','active' => '1','task' => 'REN','trigger_event' => 'PRI','for_category' => 'TM','for_country' => 'RU','detail' => '40','years' => '40'),
  array('id' => '1278','active' => '1','task' => 'REN','trigger_event' => 'PRI','for_category' => 'TM','for_country' => 'RU','detail' => '50','years' => '50'),
  array('id' => '1280','active' => '1','task' => 'PROD','trigger_event' => 'SOP','for_category' => 'PAT','for_country' => 'EP','detail' => 'Observations','days' => '10','months' => '4'),
  array('id' => '1281','active' => '1','task' => 'OPR','trigger_event' => 'SOP','for_category' => 'PAT','for_country' => 'EP','days' => '10','months' => '5'),
  array('id' => '1282','active' => '1','task' => 'PAY','trigger_event' => 'ALL','for_category' => 'TM','for_country' => 'JP','detail' => '2nd part of individual fee','months' => '3'),
  array('id' => '1290','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'SO','for_country' => 'FR','detail' => 'Soleau','years' => '5'),
  array('id' => '1291','active' => '1','task' => 'WAT','trigger_event' => 'FIL','for_category' => 'SO','for_country' => 'FR','detail' => 'End of protection','months' => '114'),
  array('id' => '1292','active' => '1','task' => 'EXP','trigger_event' => 'FIL','for_category' => 'SO','for_country' => 'FR','years' => '10'),
  array('id' => '1299','active' => '1','task' => 'OPR','trigger_event' => 'SOP','for_category' => 'OP','months' => '6'),
  array('id' => '1300','active' => '1','task' => 'PROD','trigger_event' => 'SOP','for_category' => 'OP','detail' => 'Observations','months' => '4'),
  array('id' => '1301','active' => '1','task' => 'PROD','trigger_event' => 'PRI','for_category' => 'PAT','for_country' => 'US','for_origin' => 'WO','detail' => 'Decl. and Assignment','months' => '30'),
  array('id' => '1302','active' => '1','task' => 'REQ','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'BR','years' => '3'),
  array('id' => '1303','active' => '1','task' => 'FAP','trigger_event' => 'ORE','for_category' => 'OP','for_country' => 'EP','months' => '2'),
  array('id' => '1305','active' => '1','task' => 'PRID','trigger_event' => 'FIL','for_category' => 'DSG','months' => '6','abort_on' => 'PRI','notes' => 'Priority deadline is inserted only if no priority event exists'),
  array('id' => '1306','active' => '1','task' => 'PRID','trigger_event' => 'PRI','delete_task' => '1','for_category' => 'DSG','condition_event' => 'FIL','notes' => 'Deletes priority deadline when a priority event is inserted'),
  array('id' => '1307','active' => '1','task' => 'PRID','trigger_event' => 'PRI','delete_task' => '1','for_category' => 'TM','condition_event' => 'FIL','notes' => 'Deletes priority deadline when a priority event is inserted'),
  array('id' => '1308','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'DSG','for_country' => 'WO','detail' => '1','years' => '5'),
  array('id' => '1309','active' => '1','task' => 'REN','trigger_event' => 'FIL','for_category' => 'DSG','for_country' => 'WO','detail' => '2','years' => '10'),
  array('id' => '1310','active' => '1','task' => 'PROD','trigger_event' => 'REC','for_category' => 'OPI','detail' => 'Opinion','months' => '1'),
  array('id' => '1311','active' => '1','task' => 'PROD','trigger_event' => 'REC','for_category' => 'SR','detail' => 'Report','months' => '1'),
  array('id' => '1314','active' => '1','task' => 'PROD','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'IN','detail' => 'Verification of translation','years' => '2'),
  array('id' => '1315','active' => '1','task' => 'REP','trigger_event' => 'EXA','for_category' => 'TM','for_country' => 'JP','detail' => 'Exam Report','months' => '3'),
  array('id' => '1316','active' => '1','task' => 'PROD','trigger_event' => 'EXA','for_category' => 'TM','for_country' => 'JP','detail' => 'POA','months' => '3'),
  array('id' => '1317','active' => '1','task' => 'PROD','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'IN','for_origin' => 'WO','detail' => 'Verification of translation','years' => '2'),
  array('id' => '1318','active' => '1','task' => 'PROD','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'IN','for_origin' => 'WO','detail' => 'Annexure to Form 3','years' => '2'),
  array('id' => '1319','active' => '1','task' => 'PROD','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'IN','for_origin' => 'WO','detail' => 'Declaration','years' => '2'),
  array('id' => '1320','active' => '1','task' => 'PROD','trigger_event' => 'FIL','for_category' => 'PAT','for_country' => 'IN','for_origin' => 'WO','detail' => 'Power','years' => '2'),
  array('id' => '1321','active' => '1','task' => 'PROD','trigger_event' => 'SR','for_category' => 'PAT','for_country' => 'EP','detail' => 'Analysis of SR','months' => '3'),
  array('id' => '1322','active' => '1','task' => 'PROD','trigger_event' => 'DPAPL','for_category' => 'PAT','for_country' => 'US','detail' => 'Appeal Brief','months' => '1'),
  array('id' => '1323','active' => '1','task' => 'FRCE','trigger_event' => 'EXAF','for_category' => 'PAT','for_country' => 'US','months' => '3'),
  array('id' => '1326','active' => '1','task' => 'FAP','trigger_event' => 'EXAF','for_category' => 'PAT','for_country' => 'US','months' => '3'),
  array('id' => '1327','active' => '1','task' => 'FAP','trigger_event' => 'APL','clear_task' => '1','for_category' => 'PAT'),
  array('id' => '1328','active' => '1','task' => 'PROD','trigger_event' => 'REC','for_category' => 'TM','detail' => 'Analyse CompuMark','days' => '15'),
  array('id' => '1329','active' => '1','task' => 'PROD','trigger_event' => 'REC','for_category' => 'TM','detail' => 'Libellé P/S','months' => '1'),
  array('id' => '1330','active' => '1','task' => 'PROD','trigger_event' => 'EXA','for_category' => 'PAT','detail' => 'Preliminary Comments','days' => '40'),
  array('id' => '1333','active' => '1','task' => 'REM','trigger_event' => 'DRA','for_category' => 'PAT','for_country' => 'FR','for_origin' => 'EP')
);
