<?php

namespace Tests\Feature;

use App\Models\Actor;
use App\Models\Event;
use App\Models\Matter;
use App\Models\Task;
use App\Models\User;
use Database\Seeders\DatabaseSeeder;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

/**
 * Flags of unpriced renewals in the renewal management dashboard.
 */
class RenewalDashboardTest extends TestCase
{
    use DatabaseTransactions;

    private Actor $renewr;

    protected function setUp(): void
    {
        parent::setUp();

        $this->seed(DatabaseSeeder::class);

        $this->renewr = Actor::where('name', 'LIKE', 'Renewr%')->first()
            ?? Actor::create(['name' => 'Renewr', 'phy_person' => 0]);

        $this->be(User::where('login', 'phpipuser')->firstOrFail());
    }

    /** Create a matter with a single pending renewal (year 5), priced or not. */
    private function renewal(string $caseref, string $country, string $category, array $amounts = [], bool $renewr = false, ?Actor $client = null): Matter
    {
        $matter = Matter::create([
            'caseref' => $caseref,
            'country' => $country,
            'category_code' => $category,
            'responsible' => 'phpipuser',
            'alt_ref' => '',
        ]);
        $filing = Event::create(['matter_id' => $matter->id, 'code' => 'FIL', 'event_date' => '2022-03-15']);

        // Replace the tasks generated by the rules with a single renewal
        Task::whereIn('trigger_id', Event::where('matter_id', $matter->id)->pluck('id'))->delete();
        Task::create(array_merge([
            'trigger_id' => $filing->id,
            'code' => 'REN',
            'detail' => ['en' => '5'],
            'due_date' => now()->addMonths(3)->format('Y-m-d'),
        ], $amounts));

        if ($renewr) {
            DB::table('matter_actor_lnk')->insert(['matter_id' => $matter->id, 'actor_id' => $this->renewr->id, 'role' => 'ANN', 'display_order' => 1]);
        }
        if ($client) {
            DB::table('matter_actor_lnk')->insert(['matter_id' => $matter->id, 'actor_id' => $client->id, 'role' => 'CLI', 'display_order' => 1]);
        }

        return $matter;
    }

    private function dashboard(array $filters = []): \Illuminate\Support\Collection
    {
        return collect($this->getJson('/renewal?' . http_build_query(['Case' => 'RDASH'] + $filters))
            ->assertOk()
            ->json())
            ->keyBy('caseref');
    }

    public function test_unpriced_renewals_are_flagged_by_fee_source(): void
    {
        $this->renewal('RDASH1', 'CH', 'PAT', [], true);
        $this->renewal('RDASH2', 'CH', 'TM');
        $this->renewal('RDASH3', 'CH', 'PAT', ['cost' => 500, 'fee' => 250.25], true);

        $list = $this->dashboard();

        $this->assertTrue($list['RDASH1']['pending_sync']);
        $this->assertFalse($list['RDASH1']['no_fee_source']);

        $this->assertFalse($list['RDASH2']['pending_sync']);
        $this->assertTrue($list['RDASH2']['no_fee_source']);

        $this->assertFalse($list['RDASH3']['pending_sync']);
        $this->assertFalse($list['RDASH3']['no_fee_source']);

        $this->get('/renewal?Case=RDASH')
            ->assertOk()
            ->assertSee('id="pendingSync"', false)
            ->assertSee('<span class="badge rounded-pill text-bg-warning" title="' . __('Awaiting Renewr sync since'), false)
            ->assertSee('<span class="badge rounded-pill text-bg-secondary" title="', false);
    }

    public function test_pending_sync_filter_lists_only_renewals_awaiting_renewr(): void
    {
        $this->renewal('RDASH1', 'CH', 'PAT', [], true);
        $this->renewal('RDASH2', 'CH', 'TM');
        $this->renewal('RDASH3', 'CH', 'PAT', ['cost' => 500, 'fee' => 250.25], true);

        $this->assertEquals(['RDASH1'], $this->dashboard(['pending_sync' => 1])->keys()->all());
    }

    public function test_unpriced_renewal_has_zero_fee_whatever_the_discount(): void
    {
        $client = Actor::create(['name' => 'RDASH flat discount client', 'phy_person' => 0, 'ren_discount' => 200]);
        $this->renewal('RDASH1', 'CH', 'PAT', [], true, $client);

        $renewal = $this->dashboard()['RDASH1'];

        $this->assertNull($renewal['cost']);
        $this->assertEquals(0, $renewal['fee']);
    }
}
