<?php

namespace Tests\Feature;

use App\Models\Actor;
use App\Models\Event;
use App\Models\Matter;
use App\Models\Task;
use Database\Seeders\DatabaseSeeder;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Tests\TestCase;

/**
 * Runs tasks:renewr-sync on portfolio data served from local files, without calling the Renewr API.
 */
class RenewrSyncTest extends TestCase
{
    use DatabaseTransactions;

    private string $storage;

    protected function setUp(): void
    {
        parent::setUp();

        $this->seed(DatabaseSeeder::class);

        if (!Actor::where('name', 'LIKE', 'Renewr%')->exists()) {
            Actor::create(['name' => 'Renewr', 'phy_person' => 0]);
        }

        // Keep the sync's page cache away from the real storage directory
        $this->storage = sys_get_temp_dir() . '/renewr-sync-test-' . uniqid();
        File::makeDirectory($this->storage . '/app/cache', 0755, true);
        $this->app->useStoragePath($this->storage);

        config([
            'renewr.skip_done' => true,
            'renewr.fee_calculation' => [
                'renewr_fee' => 9,
                'our_fee' => 145,
                'threshold' => 1000,
                'below_percentage' => 0.22,
                'above_percentage' => 0.165,
            ],
        ]);
    }

    protected function tearDown(): void
    {
        File::deleteDirectory($this->storage);

        parent::tearDown();
    }

    /** Create a patent with a filing event and no renewal tasks. */
    private function patent(string $caseref, string $country): Matter
    {
        $matter = Matter::create([
            'caseref' => $caseref,
            'country' => $country,
            'category_code' => 'PAT',
            'responsible' => 'phpipuser',
            'alt_ref' => '',
        ]);
        Event::create(['matter_id' => $matter->id, 'code' => 'FIL', 'event_date' => '2020-03-15']);
        Event::create(['matter_id' => $matter->id, 'code' => 'GRT', 'event_date' => '2023-03-15']);

        // Drop the renewals generated by the rules, the sync must create its own
        $this->renewals($matter)->delete();

        return $matter->refresh();
    }

    private function renewals(Matter $matter)
    {
        return Task::where('code', 'REN')
            ->whereIn('trigger_id', Event::where('matter_id', $matter->id)->pluck('id'));
    }

    private function renewal(Matter $matter, int $year): ?Task
    {
        return $this->renewals($matter)
            ->whereRaw("CAST(JSON_UNQUOTE(JSON_EXTRACT(detail, '$.\"en\"')) AS UNSIGNED) = ?", [$year])
            ->first();
    }

    private function renewrPatent(Matter $matter, array $events): array
    {
        return [
            'providerId' => $matter->id,
            'clientCaseRef' => $matter->uid,
            'country' => $matter->country,
            'renewalEvents' => $events,
        ];
    }

    private function renewrEvent(int $year, string $date, ?float $total, string $status = 'CONFIRMED'): array
    {
        return [
            'renewalYearNumber' => $year,
            'renewalDate' => $date,
            'feesStatus' => $status,
            'fees' => $total === null ? null : ['invoiceTotalValue' => $total, 'invoiceCurrency' => 'EUR'],
        ];
    }

    /** Serve the portfolio as the API response, announcing $totalPages pages. */
    private function serveApi(array $patents, int $totalPages): void
    {
        $file = $this->storage . '/api.json';
        file_put_contents($file, json_encode([
            'pagination' => ['totalItems' => count($patents), 'totalPages' => $totalPages],
            'data' => $patents,
        ]));
        config(['renewr.url' => 'file://' . $file]);
    }

    public function test_renewal_without_fees_and_faulty_patent_do_not_stop_the_sync(): void
    {
        $faulty = $this->patent('RSYNC1', 'GB');
        $good = $this->patent('RSYNC2', 'DE');

        $this->serveApi([
            // A renewal without date makes this patent fail, it is processed first
            $this->renewrPatent($faulty, [array_diff_key($this->renewrEvent(5, '2024-03-31', 509), ['renewalDate' => 0])]),
            $this->renewrPatent($good, [
                $this->renewrEvent(5, '2024-03-31', 509),
                // Renewr omits the fees of estimated renewals
                $this->renewrEvent(6, '2025-03-31', null, 'ESTIMATED'),
            ]),
        ], 1);

        // Exit code 1 flags the failed patent to the scheduler
        $this->artisan('tasks:renewr-sync')->assertExitCode(1);

        $this->assertNull($this->renewal($faulty, 5));

        $priced = $this->renewal($good, 5);
        $this->assertNotNull($priced);
        $this->assertEquals(500, $priced->cost);
        // 145 + 9 + (0.22 - 0.055 * 500 / 1000) * 500
        $this->assertEquals(250.25, $priced->fee);

        $unpriced = $this->renewal($good, 6);
        $this->assertNotNull($unpriced);
        $this->assertEquals('2025-03-31', $unpriced->due_date->format('Y-m-d'));
        $this->assertNull($unpriced->cost);
        $this->assertNull($unpriced->fee);
    }

    public function test_missing_fees_do_not_clear_existing_amounts(): void
    {
        $matter = $this->patent('RSYNC3', 'DE');

        $this->serveApi([$this->renewrPatent($matter, [$this->renewrEvent(5, '2024-03-31', 509)])], 1);
        $this->artisan('tasks:renewr-sync')->assertExitCode(0);

        // Next sync: Renewr now returns the renewal without fees and a new due date
        File::cleanDirectory($this->storage . '/app/cache');
        $this->serveApi([$this->renewrPatent($matter, [$this->renewrEvent(5, '2024-04-30', null, 'ESTIMATED')])], 1);
        $this->artisan('tasks:renewr-sync')->assertExitCode(0);

        $task = $this->renewal($matter, 5);
        $this->assertEquals('2024-04-30', $task->due_date->format('Y-m-d'));
        $this->assertEquals(500, $task->cost);
        $this->assertEquals(250.25, $task->fee);
    }

    public function test_page_count_is_taken_from_the_api_not_from_stale_metadata(): void
    {
        $matter = $this->patent('RSYNC4', 'DE');

        // Metadata left by an old run, when the portfolio had a single page
        $meta = $this->storage . '/app/cache/renewrsync_api_data_meta.json';
        file_put_contents($meta, json_encode(['totalPages' => 1, 'totalItems' => 100]));
        touch($meta, time() - 30 * 86400);

        $this->serveApi([$this->renewrPatent($matter, [$this->renewrEvent(5, '2024-03-31', 509)])], 2);

        $this->artisan('tasks:renewr-sync')->assertExitCode(0);

        $this->assertFileExists($this->storage . '/app/cache/renewrsync_api_data_page2.json');
        $this->assertEquals(2, json_decode(file_get_contents($meta))->totalPages);
    }
}
