<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Event Model
 *
 * Represents important dates and milestones in a matter's lifecycle, such as:
 * - Filing dates (FIL)
 * - Publication dates (PUB)
 * - Grant/registration dates (GRT/REG)
 * - Priority dates (PRI)
 * - Deadlines and status changes
 *
 * Database table: event
 *
 * Key relationships:
 * - Belongs to a matter
 * - Can link to an alternate matter (for priority claims, etc.)
 * - Has many tasks (automatic reminders/deadlines)
 * - Has event name info (description and classification)
 *
 * Business logic:
 * - Events automatically touch (update timestamp of) their parent matter
 * - Events can generate tasks based on rules
 * - Events can link matters together (priority, parent-child relationships)
 * - Provides methods to generate URLs to official patent/trademark registers
 */
class Event extends Model
{
    /**
     * The database table associated with the model.
     *
     * @var string
     */
    protected $table = 'event';

    /**
     * Attributes that should be hidden from serialization.
     *
     * @var array<string>
     */
    protected $hidden = ['creator', 'created_at', 'updated_at', 'updater'];

    /**
     * Attributes that are not mass assignable.
     *
     * @var array<string>
     */
    protected $guarded = ['id', 'created_at', 'updated_at'];

    /**
     * Related models that should be touched when this model is updated.
     *
     * Updates the matter's timestamp when an event changes.
     *
     * @var array<string>
     */
    protected $touches = ['matter'];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'event_date' => 'date:Y-m-d',
    ];

    /**
     * Get the event name information.
     *
     * Returns the EventName model containing description, classification,
     * and other metadata about this event type.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function info()
    {
        return $this->belongsTo(EventName::class, 'code', 'code');
    }

    /**
     * Get the matter this event belongs to.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function matter()
    {
        return $this->belongsTo(Matter::class);
    }

    /**
     * Get the alternate matter linked to this event.
     *
     * Used for priority claims, parent-child relationships, etc.
     * Returns a default empty model if no alternate matter is linked.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function altMatter()
    {
        return $this->belongsTo(Matter::class, 'alt_matter_id')->withDefault();
    }

    /**
     * Get the filing event of the alternate matter.
     *
     * Used to retrieve filing details of priority applications.
     * Returns a default empty model if no link exists.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function link()
    {
        return $this->hasOne(Event::class, 'matter_id', 'alt_matter_id')->whereCode('FIL')->withDefault();
    }

    /**
     * Get the reverse link to this event.
     *
     * Used for bidirectional event linking.
     * Returns a default empty model if no retro link exists.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function retroLink()
    {
        return $this->belongsTo(Event::class, 'matter_id', 'alt_matter_id')->withDefault();
    }

    /**
     * Get all tasks generated by this event.
     *
     * Tasks are automatic reminders and deadlines created from rules.
     * Results are ordered by due date.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function tasks()
    {
        return $this->hasMany(Task::class, 'trigger_id')->orderBy('due_date');
    }

    /**
     * Clean and normalize the event detail number.
     *
     * Removes country code prefix, spaces, commas, hyphens, slashes,
     * and decimal portions to create a standardized number format
     * suitable for URL construction and comparison.
     *
     * @return string The cleaned number
     */
    public function cleanNumber()
    {
        return preg_replace(["/^{$this->matter->country}/", '/ /', '/,/', '/-/', '/\//', '/\.[0-9]/'], '', $this->detail);
    }

    /**
     * Generate a URL to the official patent/trademark register for this event.
     *
     * Creates links to:
     * - Espacenet (worldwide patent database)
     * - EPO Register (European patents)
     * - INPI (French patents and trademarks)
     * - USPTO (US patents)
     * - IPO (UK patents)
     * - EUIPO (EU trademarks)
     *
     * Only works for filing (FIL), publication (PUB), and grant (GRT) events.
     *
     * @return string|false The URL to the official register, or false if not applicable
     */
    public function publicUrl()
    {
        if (! in_array($this->code, ['FIL', 'PUB', 'GRT'])) {
            return false;
        }
        if ($this->matter->origin == 'EP') {
            $CC = 'EP';
        } else {
            $CC = $this->matter->country;
        }
        $category = $this->matter->category_code;
        $cleanednumber = $this->cleanNumber();
        $href = '';
        $pubno = '';
        if ($this->code == 'PUB' || $this->code == 'GRT') {
            // Fix US pub number for Espacenet by keeping the last 6 digits after the year
            if ($CC == 'US' && $this->code == 'PUB') {
                $cleanednumber = substr($cleanednumber, 0, 4).substr($cleanednumber, -6);
            }
            $href = "http://worldwide.espacenet.com/publicationDetails/biblio?DB=EPODOC&CC=$CC&NR=$cleanednumber";
        } elseif ($this->code == 'FIL') {
            switch ($this->matter->country) {
                case 'EP':
                    $href = "https://register.epo.org/espacenet/application?number=EP$cleanednumber";
                    break;
                case 'FR':
                    $pubno = $this->matter->publication->cleanNumber();
                    if ($category == 'PAT' && $pubno) {
                        $href = "https://data.inpi.fr/brevets/$CC$pubno";
                    } elseif ($category == 'TM') {
                        if ($this->event_date->isoFormat('YYYY') >= '2000') {
                            $cleanednumber = substr($cleanednumber, -7);
                        }
                        $href = "https://data.inpi.fr/marques/$CC$cleanednumber";
                    }
                    break;
                case 'US':
                    if (substr($cleanednumber, 0, 2) < 13) {
                        $cleanednumber = substr($cleanednumber, 2).$this->event_date->isoFormat('YY');
                    } else {
                        $cleanednumber = $this->event_date->isoFormat('YYYY').$cleanednumber;
                    }
                    $href = "https://register.epo.org/ipfwretrieve?apn=US.$cleanednumber.A";
                    break;
                case 'GB':
                    $href = "http://www.ipo.gov.uk/p-ipsum/Case/ApplicationNumber/$CC$cleanednumber";
                    break;
                case 'EM':
                    $href = "https://euipo.europa.eu/eSearch/#details/trademarks/$cleanednumber";
                    break;
            }
        }

        return $href;
    }
}
