<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Traits\HasTableComments;
use App\Traits\HasTranslationsExtended;

/**
 * Rule Model
 *
 * Represents task generation rules that automatically create tasks when specific events occur.
 * Rules define the deadline calculation logic for IP prosecution, including:
 * - Which events trigger task creation
 * - Deadline calculation formulas (delays, months, end of month adjustments)
 * - Conditions for task generation
 * - Abort conditions that cancel pending tasks
 * - Responsible party assignments
 *
 * Database table: task_rules
 *
 * Key relationships:
 * - Belongs to country, origin, category, and type (rule applicability)
 * - Belongs to trigger event (what event creates the task)
 * - Belongs to task event name (what type of task to create)
 * - Belongs to condition event (optional prerequisite)
 * - Belongs to abort event (what cancels the task)
 * - Belongs to responsible actor (who is assigned the task)
 * - Has many templates for document generation
 *
 * Business logic:
 * - Rules are evaluated when events are created or updated
 * - Rules can have complex conditions (event presence, actor roles, etc.)
 * - Deadline calculation supports various date arithmetic
 * - Task details are translatable for multi-language support
 * - Rules can be country/category/type-specific or generic
 */
class Rule extends Model
{
    use HasTableComments;
    use HasTranslationsExtended;

    /**
     * The database table associated with the model.
     *
     * @var string
     */
    protected $table = 'task_rules';

    /**
     * Attributes that should be hidden from serialization.
     *
     * @var array<string>
     */
    protected $hidden = ['creator', 'created_at', 'updated_at', 'updater'];

    /**
     * Attributes that are not mass assignable.
     *
     * @var array<string>
     */
    protected $guarded = ['id', 'created_at', 'updated_at'];

    /**
     * Attributes that support multi-language translations.
     *
     * @var array<string>
     */
    public $translatable = ['detail'];

    /**
     * Get the country this rule applies to.
     *
     * Rules can be country-specific or apply to all countries if null.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function country()
    {
        return $this->belongsTo(Country::class, 'for_country', 'iso');
    }

    /**
     * Get the origin country this rule applies to.
     *
     * Used for rules that depend on the matter's origin (e.g., PCT rules).
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function origin()
    {
        return $this->belongsTo(Country::class, 'for_origin', 'iso');
    }

    /**
     * Get the category this rule applies to.
     *
     * Rules can be category-specific (PAT, TM, etc.) or apply to all categories if null.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category()
    {
        return $this->belongsTo(Category::class, 'for_category', 'code');
    }

    /**
     * Get the event that triggers this rule.
     *
     * When this event occurs, the rule is evaluated for task creation.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function trigger()
    {
        return $this->belongsTo(EventName::class, 'trigger_event');
    }

    /**
     * Get the task event name information.
     *
     * Defines what type of task this rule creates.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function taskInfo()
    {
        return $this->belongsTo(EventName::class, 'task');
    }

    /**
     * Get the matter type this rule applies to.
     *
     * Rules can be type-specific or apply to all types if null.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function type()
    {
        return $this->belongsTo(MatterType::class, 'for_type', 'code');
    }

    /**
     * Get the condition event information.
     *
     * If specified, this event must exist for the rule to generate a task.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function condition_eventInfo()
    {
        return $this->belongsTo(EventName::class, 'condition_event');
    }

    /**
     * Get the abort event information.
     *
     * If this event occurs, any pending tasks generated by this rule are cancelled.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function abort_onInfo()
    {
        return $this->belongsTo(EventName::class, 'abort_on');
    }

    /**
     * Get the responsible actor for tasks generated by this rule.
     *
     * If specified, tasks are assigned to this actor instead of the matter's responsible.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function responsibleInfo()
    {
        return $this->belongsTo(Actor::class, 'responsible', 'login');
    }

    /**
     * Get the document templates associated with this rule.
     *
     * Templates can be used to generate documents when the task is processed.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function templates()
    {
        return $this->belongsToMany(TemplateClass::class, 'rule_class_lnk', 'task_rule_id', 'template_class_id');
    }
}
